// ..\dev\assets\enems_potipoti.h
// Generated by eneexp3.exe v0.2 [20160731]
// Copyleft 2016 The Mojon Twins

// Enems structure is {T YX1 YX2 P} x 3 x MAP_W x MAP_H
// y coordinates are adjusted by 1 positions
const unsigned char enems_potipoti [] = {
	0x23, 0xAA, 0xAE, 0x02, 0x11, 0x19, 0xA9, 0x04, 
	0x10, 0xA4, 0xA2, 0x01};

// Hotspots structure is {T YX} x MAP_W x MAP_H
const unsigned char hotspots_potipoti [] = {
	0x01, 0x9F};

#define MAX_HOTSPOTS_POTIPOTI_TYPE_1	1
