;this file for FamiTone2 library generated by text2data tool

music_music_data:
	.byte 4
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256
	.word @song1ch0,@song1ch1,@song1ch2,@song1ch3,@song1ch4,307,256
	.word @song2ch0,@song2ch1,@song2ch2,@song2ch3,@song2ch4,307,256
	.word @song3ch0,@song3ch1,@song3ch2,@song3ch3,@song3ch4,307,256

@instruments:
	.byte $30 ;instrument $00
	.word @env2,@env0,@env0
	.byte $00
	.byte $30 ;instrument $01
	.word @env1,@env0,@env15
	.byte $00
	.byte $30 ;instrument $02
	.word @env4,@env0,@env0
	.byte $00
	.byte $30 ;instrument $03
	.word @env5,@env13,@env0
	.byte $00
	.byte $30 ;instrument $04
	.word @env8,@env14,@env0
	.byte $00
	.byte $30 ;instrument $05
	.word @env12,@env0,@env0
	.byte $00
	.byte $30 ;instrument $06
	.word @env10,@env0,@env0
	.byte $00
	.byte $30 ;instrument $07
	.word @env3,@env0,@env0
	.byte $00
	.byte $30 ;instrument $08
	.word @env1,@env0,@env15
	.byte $00
	.byte $70 ;instrument $09
	.word @env6,@env0,@env0
	.byte $00
	.byte $30 ;instrument $0a
	.word @env5,@env13,@env0
	.byte $00
	.byte $30 ;instrument $0b
	.word @env7,@env14,@env0
	.byte $00
	.byte $30 ;instrument $0c
	.word @env11,@env0,@env0
	.byte $00
	.byte $30 ;instrument $0d
	.word @env9,@env0,@env0
	.byte $00

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $c1,$c3,$c7,$c9,$00,$03
@env2:
	.byte $cc,$00,$00
@env3:
	.byte $ce,$00,$00
@env4:
	.byte $c9,$07,$c6,$05,$c9,$07,$c9,$00,$06
@env5:
	.byte $c8,$00,$00
@env6:
	.byte $ca,$07,$c7,$05,$ca,$07,$ca,$00,$06
@env7:
	.byte $cd,$cb,$c9,$c8,$c5,$c3,$c1,$c0,$00,$07
@env8:
	.byte $cf,$cd,$cb,$c9,$c7,$c5,$c3,$c1,$c0,$00,$08
@env9:
	.byte $c7,$c2,$c0,$00,$02
@env10:
	.byte $ca,$c5,$c3,$c2,$c0,$00,$04
@env11:
	.byte $cc,$ca,$c8,$c6,$c4,$c3,$c2,$c1,$c0,$00,$08
@env12:
	.byte $cd,$cc,$ca,$c9,$c7,$c6,$c5,$c3,$c0,$00,$08
@env13:
	.byte $cc,$c0,$00,$01
@env14:
	.byte $c7,$c3,$c0,$bd,$00,$02
@env15:
	.byte $c0,$0e,$bf,$be,$bd,$bc,$bd,$be,$bf,$c0,$00,$02


@song0ch0:
	.byte $fb,$04
@song0ch0loop:
@ref0:
	.byte $82,$40,$8d,$3a,$85,$32,$85,$42,$8d,$46,$85,$42,$85
@ref1:
	.byte $40,$8d,$3a,$85,$32,$85,$42,$8d,$46,$85,$42,$85
@ref2:
	.byte $4a,$8d,$40,$85,$3a,$85,$46,$85,$42,$85,$40,$85,$42,$85
	.byte $ff,$0e
	.word @ref2
	.byte $ff,$0c
	.word @ref1
	.byte $ff,$0c
	.word @ref1
	.byte $ff,$0e
	.word @ref2
	.byte $ff,$0e
	.word @ref2
@ref8:
	.byte $32,$9d,$34,$9d
@ref9:
	.byte $32,$85,$40,$b5
@ref10:
	.byte $3a,$bd
@ref11:
	.byte $4a,$bd
@ref12:
	.byte $32,$bd
@ref13:
	.byte $87,$40,$85,$42,$85,$46,$85,$4a,$85,$46,$85,$42,$85,$3c,$85
@ref14:
	.byte $3a,$bd
@ref15:
	.byte $87,$36,$85,$3a,$85,$3c,$85,$40,$85,$42,$85,$40,$85,$3c,$85
@ref16:
	.byte $84,$40,$85,$41,$41,$3a,$85,$00,$8d,$42,$85,$46,$85,$00,$85
@ref17:
	.byte $40,$85,$41,$41,$3a,$85,$00,$8d,$42,$85,$46,$85,$42,$85
@ref18:
	.byte $40,$85,$41,$41,$3a,$85,$00,$8d,$42,$85,$46,$85,$00,$85
	.byte $ff,$0e
	.word @ref17
	.byte $fd
	.word @song0ch0loop

@song0ch1:
@song0ch1loop:
@ref20:
	.byte $00,$83,$82,$40,$8d,$3a,$85,$32,$85,$42,$8d,$46,$85,$42
@ref21:
	.byte $85,$40,$8d,$3a,$85,$32,$85,$42,$8d,$46,$85,$42
@ref22:
	.byte $85,$4a,$8d,$40,$85,$3a,$85,$46,$85,$42,$85,$40,$85,$42
	.byte $ff,$0e
	.word @ref22
@ref24:
	.byte $84,$40,$95,$40,$85,$42,$95,$42,$85
@ref25:
	.byte $40,$85,$3c,$8d,$3c,$85,$34,$85,$3c,$85,$4c,$8d
@ref26:
	.byte $4a,$9d,$4c,$9d
@ref27:
	.byte $4a,$9d,$46,$9d
@ref28:
	.byte $01,$32,$9d,$34,$99
@ref29:
	.byte $8b,$41,$42,$85,$46,$85,$4a,$85,$46,$85,$42,$85,$3c,$85
@ref30:
	.byte $83,$3a,$b9
	.byte $ff,$0f
	.word @ref15
@ref32:
	.byte $4b,$4b,$4f,$4b,$4b,$4f,$53,$55,$52,$8d,$4e,$85,$4a,$85
@ref33:
	.byte $87,$4a,$85,$52,$85,$58,$85,$4c,$85,$4c,$85,$54,$85,$5a,$85
@ref34:
	.byte $80,$3a,$95,$40,$8d,$34,$8d,$32,$85
@ref35:
	.byte $87,$42,$b5
@ref36:
	.byte $86,$59,$4b,$53,$55,$59,$4b,$53,$55,$59,$4b,$53,$55,$59,$4b,$53
	.byte $54,$81
@ref37:
	.byte $59,$4b,$53,$55,$59,$4b,$53,$55,$59,$4b,$53,$55,$59,$4b,$53,$54
	.byte $81
@ref38:
	.byte $5b,$4d,$55,$59,$5b,$4d,$55,$59,$5b,$4d,$55,$59,$5b,$4d,$55,$58
	.byte $81
@ref39:
	.byte $82,$46,$a7,$84,$42,$85,$46,$85,$42,$83
	.byte $fd
	.word @song0ch1loop

@song0ch2:
@song0ch2loop:
@ref40:
	.byte $80,$32,$85,$32,$85,$3a,$85,$40,$85,$34,$85,$34,$85,$3c,$85,$42
	.byte $85
@ref41:
	.byte $32,$85,$32,$85,$3a,$85,$40,$85,$34,$85,$34,$85,$3c,$85,$42,$85
	.byte $ff,$10
	.word @ref41
	.byte $ff,$10
	.word @ref41
@ref44:
	.byte $1b,$32,$32,$33,$1b,$32,$32,$33,$1b,$32,$32,$25,$3c,$3c,$3d,$25
	.byte $3c,$3c,$3d,$25,$3c,$3c
@ref45:
	.byte $23,$3a,$3a,$3b,$23,$3a,$3a,$3b,$23,$3a,$3a,$1d,$1d,$35,$1d,$1d
	.byte $35,$21,$38,$81
	.byte $ff,$16
	.word @ref44
	.byte $ff,$14
	.word @ref45
@ref48:
	.byte $32,$85,$32,$85,$34,$85,$32,$85,$34,$85,$3a,$85,$34,$85,$32,$85
@ref49:
	.byte $32,$85,$32,$85,$34,$85,$32,$85,$34,$85,$3a,$85,$32,$85,$34,$85
@ref50:
	.byte $32,$8d,$34,$85,$32,$85,$34,$85,$3a,$85,$34,$85,$32,$83,$32
@ref51:
	.byte $22,$85,$3a,$3a,$3b,$22,$85,$3b,$3a,$3a,$1c,$85,$34,$34,$35,$1c
	.byte $85,$35,$34,$34
	.byte $ff,$10
	.word @ref48
	.byte $ff,$10
	.word @ref49
	.byte $ff,$0f
	.word @ref50
	.byte $ff,$14
	.word @ref51
@ref56:
	.byte $32,$85,$32,$85,$3a,$85,$3a,$85,$34,$85,$34,$85,$3c,$85,$34,$85
@ref57:
	.byte $32,$85,$32,$85,$3a,$85,$3a,$85,$34,$85,$34,$85,$3c,$85,$42,$85
	.byte $ff,$10
	.word @ref56
	.byte $ff,$10
	.word @ref57
	.byte $fd
	.word @song0ch2loop

@song0ch3:
@song0ch3loop:
@ref60:
	.byte $8a,$21,$8c,$1b,$8a,$21,$21,$88,$21,$8c,$1b,$8a,$21,$8c,$1b,$8a
	.byte $21,$8c,$1b,$8a,$21,$21,$88,$21,$8c,$1b,$8a,$21,$8c,$1a,$81
@ref61:
	.byte $8a,$20,$8c,$1a,$1e,$1a,$8a,$21,$21,$88,$21,$8c,$1b,$8a,$21,$8c
	.byte $1b,$8a,$21,$8c,$1b,$8a,$21,$21,$88,$21,$8a,$21,$88,$21,$8a,$1a
	.byte $81
@ref62:
	.byte $21,$8c,$1b,$8a,$21,$21,$88,$21,$8c,$1b,$8a,$21,$8c,$1b,$8a,$21
	.byte $8c,$1b,$8a,$21,$21,$88,$21,$8c,$1b,$8a,$21,$8c,$1a,$81
	.byte $ff,$13
	.word @ref61
	.byte $ff,$11
	.word @ref62
	.byte $ff,$13
	.word @ref61
	.byte $ff,$11
	.word @ref62
	.byte $ff,$13
	.word @ref61
@ref68:
	.byte $21,$8c,$1b,$1f,$1b,$8a,$21,$8c,$1b,$1f,$1b,$8a,$21,$8c,$1b,$1f
	.byte $1b,$8a,$21,$8c,$1b,$8a,$21,$20,$81
@ref69:
	.byte $21,$1b,$8c,$1b,$1f,$8a,$21,$8c,$1a,$1e,$1a,$1e,$1b,$8a,$21,$8c
	.byte $1b,$1f,$1b,$8a,$21,$8c,$1b,$8a,$21,$20,$81
	.byte $ff,$11
	.word @ref68
	.byte $ff,$13
	.word @ref69
	.byte $ff,$11
	.word @ref68
	.byte $ff,$13
	.word @ref69
	.byte $ff,$11
	.word @ref68
	.byte $ff,$13
	.word @ref69
@ref76:
	.byte $21,$8c,$1b,$8a,$21,$8c,$1b,$88,$21,$8c,$1b,$8a,$20,$8c,$1a,$8a
	.byte $21,$8c,$1b,$8a,$21,$21,$8c,$1b,$88,$21,$8c,$1b,$1f,$1a,$81
@ref77:
	.byte $8a,$21,$8c,$1b,$8a,$21,$8c,$1b,$88,$21,$8c,$1a,$1e,$8a,$20,$8c
	.byte $1a,$1e,$1a,$1f,$8a,$1b,$21,$8c,$1b,$88,$21,$8a,$21,$88,$21,$8a
	.byte $20,$81
	.byte $ff,$12
	.word @ref76
@ref79:
	.byte $8a,$21,$8c,$1b,$8a,$21,$8c,$1b,$88,$21,$8c,$1b,$88,$21,$1f,$21
	.byte $21,$1f,$1f,$03,$03,$21,$20,$81
	.byte $fd
	.word @song0ch3loop

@song0ch4:
@song0ch4loop:
@ref80:
	.byte $bf
@ref81:
	.byte $bf
@ref82:
	.byte $bf
@ref83:
	.byte $bf
@ref84:
	.byte $bf
@ref85:
	.byte $bf
@ref86:
	.byte $bf
@ref87:
	.byte $bf
@ref88:
	.byte $bf
@ref89:
	.byte $bf
@ref90:
	.byte $bf
@ref91:
	.byte $bf
@ref92:
	.byte $bf
@ref93:
	.byte $bf
@ref94:
	.byte $bf
@ref95:
	.byte $bf
@ref96:
	.byte $bf
@ref97:
	.byte $bf
@ref98:
	.byte $bf
@ref99:
	.byte $bf
	.byte $fd
	.word @song0ch4loop


@song1ch0:
	.byte $fb,$08
@song1ch0loop:
@ref100:
	.byte $00,$bd
@ref101:
	.byte $00,$bd
@ref102:
	.byte $92,$30,$00,$30,$30,$30,$00,$30,$30,$30,$00,$34,$83,$38,$83,$3a
	.byte $00,$3a,$3a,$3a,$00,$3a,$3a,$3a,$00,$3a,$3b,$3a,$3a,$81
@ref103:
	.byte $30,$00,$30,$30,$30,$00,$30,$30,$30,$00,$34,$83,$38,$83,$3a,$00
	.byte $3a,$3a,$3a,$00,$3a,$3a,$3a,$00,$3a,$3b,$3a,$3a,$81
@ref104:
	.byte $90,$48,$89,$49,$4c,$89,$4d,$52,$89,$53,$48,$85,$4d,$50,$81
@ref105:
	.byte $48,$89,$49,$4c,$89,$4d,$52,$89,$53,$48,$85,$4d,$50,$81
@ref106:
	.byte $00,$bd
@ref107:
	.byte $00,$bd
	.byte $ff,$1d
	.word @ref102
	.byte $ff,$1d
	.word @ref103
	.byte $ff,$0e
	.word @ref104
	.byte $ff,$0e
	.word @ref105
@ref112:
	.byte $30,$95,$31,$2c,$85,$30,$89,$36,$85,$30,$85
@ref113:
	.byte $3a,$85,$3f,$3a,$91,$2d,$36,$85,$2d,$37,$2c,$85,$2c,$81
	.byte $ff,$0b
	.word @ref112
	.byte $ff,$0e
	.word @ref113
@ref116:
	.byte $3e,$8d,$36,$8d,$3a,$8d,$36,$85,$3a,$85
	.byte $ff,$0a
	.word @ref116
	.byte $ff,$0a
	.word @ref116
	.byte $ff,$0a
	.word @ref116
@ref120:
	.byte $94,$3f,$31,$3f,$31,$3f,$31,$3f,$31,$2d,$3f,$2d,$3f,$2d,$3f,$2d
	.byte $30,$81
	.byte $fd
	.word @song1ch0loop

@song1ch1:
@song1ch1loop:
@ref121:
	.byte $94,$18,$00,$18,$18,$18,$00,$18,$18,$18,$00,$1c,$83,$20,$83,$22
	.byte $00,$22,$22,$22,$00,$22,$22,$22,$00,$22,$23,$22,$22,$81
@ref122:
	.byte $18,$00,$18,$18,$18,$00,$18,$18,$18,$00,$1c,$83,$20,$83,$22,$00
	.byte $22,$22,$22,$00,$22,$22,$22,$00,$22,$23,$22,$22,$81
@ref123:
	.byte $90,$42,$85,$3e,$8d,$3a,$38,$83,$3a,$85,$38,$8d,$34,$30,$83
@ref124:
	.byte $42,$85,$3e,$8d,$3a,$38,$83,$3a,$85,$38,$8d,$34,$30,$83
@ref125:
	.byte $92,$48,$00,$48,$48,$48,$00,$48,$48,$4d,$50,$4d,$49,$00,$48,$00
	.byte $48,$48,$48,$48,$00,$48,$52,$50,$48,$4d,$49,$3e
@ref126:
	.byte $48,$00,$48,$48,$48,$00,$48,$48,$4d,$50,$4d,$49,$00,$48,$00,$48
	.byte $48,$48,$48,$00,$48,$52,$50,$48,$4d,$49,$3e
	.byte $ff,$1d
	.word @ref121
	.byte $ff,$1d
	.word @ref122
	.byte $ff,$0e
	.word @ref123
	.byte $ff,$0e
	.word @ref124
	.byte $ff,$1b
	.word @ref125
	.byte $ff,$1b
	.word @ref126
@ref133:
	.byte $49,$49,$45,$45,$4f,$4f,$49,$44,$85,$49,$45,$45,$4f,$4f,$49,$4e
	.byte $81
@ref134:
	.byte $52,$85,$57,$52,$91,$45,$4e,$85,$45,$4f,$44,$85,$44,$81
	.byte $ff,$11
	.word @ref133
	.byte $ff,$0e
	.word @ref134
@ref137:
	.byte $56,$85,$59,$56,$89,$48,$85,$57,$48,$85,$44,$85,$4e,$85,$52,$81
@ref138:
	.byte $87,$57,$4e,$91,$52,$85,$56,$85,$4e,$85,$52,$85
	.byte $ff,$10
	.word @ref137
	.byte $ff,$10
	.word @ref137
@ref141:
	.byte $56,$85,$59,$56,$89,$48,$85,$57,$48,$85,$44,$85,$4e,$89
	.byte $fd
	.word @song1ch1loop

@song1ch2:
@song1ch2loop:
@ref142:
	.byte $00,$bd
@ref143:
	.byte $00,$bd
@ref144:
	.byte $8e,$19,$19,$31,$19,$19,$1c,$35,$20,$39,$23,$23,$3b,$23,$23,$22
	.byte $3b,$22,$3a,$81
@ref145:
	.byte $19,$19,$31,$19,$19,$1c,$35,$20,$39,$23,$23,$3b,$23,$23,$22,$3b
	.byte $22,$3a,$81
	.byte $ff,$13
	.word @ref145
	.byte $ff,$13
	.word @ref145
	.byte $ff,$13
	.word @ref145
	.byte $ff,$13
	.word @ref145
	.byte $ff,$13
	.word @ref145
	.byte $ff,$13
	.word @ref145
	.byte $ff,$13
	.word @ref145
	.byte $ff,$13
	.word @ref145
@ref154:
	.byte $31,$01,$30,$00,$31,$30,$00,$30,$00,$30,$00,$30,$00,$2d,$01,$2c
	.byte $00,$2d,$2c,$00,$2c,$00,$2c,$00,$2c,$00
@ref155:
	.byte $29,$01,$28,$00,$29,$28,$00,$28,$00,$28,$00,$28,$00,$2d,$01,$2c
	.byte $00,$2d,$2c,$00,$2c,$00,$2c,$00,$2c,$00
	.byte $ff,$1a
	.word @ref154
	.byte $ff,$1a
	.word @ref155
	.byte $ff,$1a
	.word @ref154
	.byte $ff,$1a
	.word @ref155
	.byte $ff,$1a
	.word @ref154
	.byte $ff,$1a
	.word @ref155
	.byte $ff,$1a
	.word @ref155
	.byte $fd
	.word @song1ch2loop

@song1ch3:
@song1ch3loop:
@ref163:
	.byte $98,$21,$9a,$1b,$96,$21,$9a,$1b,$98,$21,$9a,$1b,$96,$21,$9a,$1b
	.byte $98,$21,$9a,$1b,$96,$21,$9a,$1b,$98,$21,$9a,$1b,$96,$21,$98,$20
	.byte $81
@ref164:
	.byte $21,$9a,$1b,$96,$21,$9a,$1b,$98,$21,$9a,$1b,$96,$21,$9a,$1b,$98
	.byte $21,$9a,$1b,$96,$21,$98,$20,$20,$96,$20,$20,$98,$20,$20,$96,$20
	.byte $20,$20,$20
@ref165:
	.byte $98,$21,$21,$96,$21,$98,$20,$20,$21,$9a,$1b,$96,$21,$9a,$1b,$98
	.byte $21,$21,$96,$21,$9a,$1b,$98,$21,$21,$96,$21,$20,$20
	.byte $ff,$12
	.word @ref165
	.byte $ff,$11
	.word @ref163
	.byte $ff,$15
	.word @ref164
	.byte $ff,$11
	.word @ref163
	.byte $ff,$15
	.word @ref164
	.byte $ff,$12
	.word @ref165
	.byte $ff,$12
	.word @ref165
@ref173:
	.byte $98,$21,$9a,$1b,$96,$21,$9a,$1b,$98,$21,$9a,$1b,$96,$21,$9a,$1b
	.byte $98,$21,$9a,$1b,$96,$21,$98,$20,$20,$96,$20,$20,$98,$20,$20,$96
	.byte $20,$20,$20,$20
	.byte $ff,$15
	.word @ref173
	.byte $ff,$12
	.word @ref165
	.byte $ff,$12
	.word @ref165
	.byte $ff,$12
	.word @ref165
	.byte $ff,$12
	.word @ref165
	.byte $ff,$15
	.word @ref173
	.byte $ff,$15
	.word @ref173
	.byte $ff,$15
	.word @ref173
@ref182:
	.byte $98,$21,$9a,$1b,$96,$21,$21,$98,$21,$96,$20,$00,$21,$98,$20,$20
	.byte $21,$9a,$1b,$96,$20,$20,$98,$20,$20,$96,$20,$20,$98,$20,$20,$96
	.byte $20,$20,$20,$20
	.byte $ff,$18
	.word @ref182
	.byte $fd
	.word @song1ch3loop

@song1ch4:
@song1ch4loop:
@ref184:
	.byte $bf
@ref185:
	.byte $bf
@ref186:
	.byte $bf
@ref187:
	.byte $bf
@ref188:
	.byte $bf
@ref189:
	.byte $bf
@ref190:
	.byte $bf
@ref191:
	.byte $bf
@ref192:
	.byte $bf
@ref193:
	.byte $bf
@ref194:
	.byte $bf
@ref195:
	.byte $bf
@ref196:
	.byte $bf
@ref197:
	.byte $bf
@ref198:
	.byte $bf
@ref199:
	.byte $bf
@ref200:
	.byte $bf
@ref201:
	.byte $bf
@ref202:
	.byte $bf
@ref203:
	.byte $bf
@ref204:
	.byte $bf
	.byte $fd
	.word @song1ch4loop


@song2ch0:
	.byte $fb,$03
@ref205:
	.byte $84,$32,$85,$32,$85,$32,$85,$36,$95,$32,$85,$32,$85,$32,$85,$36
	.byte $8d,$86,$3a,$85,$84,$32,$85,$36,$85,$3a,$85,$32,$85
@ref206:
	.byte $40,$85,$3c,$85,$3a,$85,$32,$85,$40,$85,$3c,$85,$3c,$85,$3a,$8d
	.byte $32,$b5
@ref207:
	.byte $8f
@song2ch0loop:
@ref208:
	.byte $00
	.byte $fd
	.word @song2ch0loop

@song2ch1:
@ref209:
	.byte $86,$58,$85,$58,$8d,$54,$8d,$54,$85,$52,$85,$4a,$a5,$4a,$85,$4e
	.byte $85,$52,$85,$4a,$85
@ref210:
	.byte $58,$8d,$52,$85,$82,$32,$e5
@ref211:
	.byte $8f
@song2ch1loop:
@ref212:
	.byte $00
	.byte $fd
	.word @song2ch1loop

@song2ch2:
@ref213:
	.byte $80,$32,$85,$32,$85,$32,$85,$36,$85,$36,$85,$36,$85,$32,$85,$32
	.byte $85,$32,$85,$36,$85,$36,$85,$36,$85,$32,$85,$36,$85,$3a,$85,$32
	.byte $85
@ref214:
	.byte $40,$85,$3c,$85,$3a,$85,$32,$ad,$32,$b5
@ref215:
	.byte $8f
@song2ch2loop:
@ref216:
	.byte $00
	.byte $fd
	.word @song2ch2loop

@song2ch3:
@ref217:
	.byte $8a,$21,$8c,$1b,$8a,$21,$8c,$1b,$88,$21,$8c,$1b,$8a,$21,$8c,$1b
	.byte $8a,$21,$21,$88,$21,$8c,$1b,$8a,$21,$8c,$1b,$8a,$21,$8c,$1b,$88
	.byte $21,$8c,$1b,$8a,$21,$8c,$1b,$8a,$21,$8c,$1b,$8a,$21,$8c,$1b,$88
	.byte $21,$21,$1f,$1f,$03,$03,$21,$20,$81
@ref218:
	.byte $20,$85,$20,$85,$21,$21,$20,$e5
@ref219:
	.byte $8f
@song2ch3loop:
@ref220:
	.byte $00
	.byte $fd
	.word @song2ch3loop

@song2ch4:
@ref221:
	.byte $f9,$85
@ref222:
	.byte $f9,$85
@ref223:
	.byte $8f
@song2ch4loop:
@ref224:
	.byte $81
	.byte $fd
	.word @song2ch4loop


@song3ch0:
	.byte $fb,$03
@ref225:
	.byte $90,$1a,$85,$1e,$85,$1a,$85,$26,$8d,$26,$8d,$26,$85,$24,$8d,$38
	.byte $8d,$38,$85,$3c,$85,$32,$8d
@ref226:
	.byte $9f,$fb,$09,$9f
@song3ch0loop:
@ref227:
	.byte $00
	.byte $fd
	.word @song3ch0loop

@song3ch1:
@ref228:
	.byte $92,$32,$85,$36,$85,$32,$85,$3e,$8d,$3e,$8d,$3e,$85,$3c,$8d,$50
	.byte $8d,$50,$85,$54,$85,$4a,$8d
@ref229:
	.byte $bf
@song3ch1loop:
@ref230:
	.byte $00
	.byte $fd
	.word @song3ch1loop

@song3ch2:
@ref231:
	.byte $8e,$32,$85,$36,$85,$32,$85,$3e,$8d,$3e,$8d,$3e,$85,$3c,$8d,$38
	.byte $8d,$38,$85,$3c,$85,$32,$8d
@ref232:
	.byte $bf
@song3ch2loop:
@ref233:
	.byte $00
	.byte $fd
	.word @song3ch2loop

@song3ch3:
@ref234:
	.byte $98,$21,$9a,$1b,$98,$21,$9a,$1b,$98,$21,$9a,$1b,$98,$21,$9a,$1b
	.byte $98,$21,$9a,$1b,$96,$21,$9a,$1b,$98,$21,$9a,$1b,$98,$21,$9a,$1b
	.byte $98,$21,$9a,$1b,$96,$21,$98,$21,$21,$21,$96,$21,$21,$98,$21,$21
	.byte $96,$21,$21,$20,$8d
@ref235:
	.byte $bf
@song3ch3loop:
@ref236:
	.byte $00
	.byte $fd
	.word @song3ch3loop

@song3ch4:
@ref237:
	.byte $f9,$85
@ref238:
	.byte $bf
@song3ch4loop:
@ref239:
	.byte $81
	.byte $fd
	.word @song3ch4loop
