;this file for FamiTone2 library generated by text2data tool

music_music_data:
	.byte 3
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256
	.word @song1ch0,@song1ch1,@song1ch2,@song1ch3,@song1ch4,256,213
	.word @song2ch0,@song2ch1,@song2ch2,@song2ch3,@song2ch4,307,256

@instruments:
	.byte $30 ;instrument $00
	.word @env2,@env0,@env0
	.byte $00
	.byte $30 ;instrument $01
	.word @env1,@env0,@env19
	.byte $00
	.byte $70 ;instrument $02
	.word @env5,@env0,@env0
	.byte $00
	.byte $30 ;instrument $03
	.word @env6,@env16,@env0
	.byte $00
	.byte $30 ;instrument $04
	.word @env7,@env18,@env0
	.byte $00
	.byte $30 ;instrument $05
	.word @env11,@env0,@env0
	.byte $00
	.byte $30 ;instrument $06
	.word @env8,@env0,@env0
	.byte $00
	.byte $30 ;instrument $07
	.word @env1,@env17,@env0
	.byte $00
	.byte $70 ;instrument $08
	.word @env3,@env0,@env20
	.byte $00
	.byte $70 ;instrument $09
	.word @env4,@env0,@env20
	.byte $00
	.byte $30 ;instrument $0a
	.word @env3,@env0,@env20
	.byte $00
	.byte $30 ;instrument $0f
	.word @env10,@env0,@env0
	.byte $00
	.byte $30 ;instrument $10
	.word @env9,@env0,@env19
	.byte $00
	.byte $70 ;instrument $11
	.word @env5,@env0,@env0
	.byte $00
	.byte $30 ;instrument $12
	.word @env12,@env16,@env0
	.byte $00
	.byte $30 ;instrument $13
	.word @env13,@env18,@env0
	.byte $00
	.byte $30 ;instrument $14
	.word @env15,@env0,@env0
	.byte $00
	.byte $30 ;instrument $15
	.word @env14,@env0,@env0
	.byte $00

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $ca,$00,$00
@env2:
	.byte $cf,$00,$00
@env3:
	.byte $cc,$cb,$ca,$ca,$c9,$03,$c8,$03,$c7,$07,$c6,$08,$c5,$0a,$c4,$0c
	.byte $c3,$0c,$c2,$12,$c1,$19,$c0,$00,$16
@env4:
	.byte $c4,$02,$c3,$0c,$c2,$0b,$c1,$12,$c0,$00,$08
@env5:
	.byte $c9,$07,$c6,$05,$c9,$07,$c9,$00,$06
@env6:
	.byte $c6,$00,$00
@env7:
	.byte $cc,$ca,$c8,$c6,$c4,$c2,$c0,$00,$06
@env8:
	.byte $c7,$c2,$c0,$00,$02
@env9:
	.byte $c1,$c3,$c7,$c9,$00,$03
@env10:
	.byte $cc,$00,$00
@env11:
	.byte $cd,$cb,$c9,$c7,$c5,$c4,$c3,$c2,$c0,$00,$08
@env12:
	.byte $c8,$00,$00
@env13:
	.byte $cf,$cd,$cb,$c9,$c7,$c5,$c3,$c1,$c0,$00,$08
@env14:
	.byte $ca,$c5,$c3,$c2,$c0,$00,$04
@env15:
	.byte $cd,$cc,$ca,$c9,$c7,$c6,$c5,$c3,$c0,$00,$08
@env16:
	.byte $cc,$c0,$00,$01
@env17:
	.byte $c0,$05,$bf,$be,$bd,$bc,$bb,$ba,$b9,$b8,$b7,$b6,$b5,$b4,$b3,$b2
	.byte $b1,$b0,$af,$ae,$ad,$ac,$ab,$aa,$a9,$a8,$a8,$a7,$a7,$a6,$a6,$a5
	.byte $a5,$a4,$a4,$a3,$a3,$a2,$a2,$a1,$a1,$00,$28
@env18:
	.byte $c7,$c3,$c0,$bd,$00,$02
@env19:
	.byte $c0,$0e,$bf,$be,$bd,$bc,$bd,$be,$bf,$c0,$00,$02
@env20:
	.byte $c0,$0f,$c1,$02,$c2,$02,$c1,$02,$c0,$c0,$c0,$00,$02


@song0ch0:
	.byte $fb,$04
@song0ch0loop:
@ref0:
	.byte $98,$40,$8d,$3a,$85,$32,$85,$42,$8d,$46,$85,$42,$85
@ref1:
	.byte $40,$8d,$3a,$85,$32,$85,$42,$8d,$46,$85,$42,$85
@ref2:
	.byte $4a,$8d,$40,$85,$3a,$85,$46,$85,$42,$85,$40,$85,$42,$85
	.byte $ff,$0e
	.word @ref2
@ref4:
	.byte $9c,$59,$53,$4b,$53,$59,$53,$4b,$53,$59,$53,$4b,$53,$59,$53,$4b
	.byte $52,$81
@ref5:
	.byte $5b,$55,$4d,$55,$5b,$55,$4d,$55,$5b,$55,$4d,$55,$5b,$55,$4d,$54
	.byte $81
@ref6:
	.byte $62,$89,$5b,$59,$55,$52,$8d,$5a,$85,$58,$85,$5a,$85
@ref7:
	.byte $62,$89,$5b,$59,$5b,$55,$53,$5e,$85,$5a,$85,$58,$85,$5a,$85
@ref8:
	.byte $98,$32,$9d,$34,$9d
@ref9:
	.byte $32,$85,$40,$b5
@ref10:
	.byte $3a,$bd
@ref11:
	.byte $4a,$bd
@ref12:
	.byte $32,$bd
@ref13:
	.byte $87,$40,$85,$42,$85,$46,$85,$4a,$85,$46,$85,$42,$85,$3c,$85
@ref14:
	.byte $3a,$bd
@ref15:
	.byte $87,$36,$85,$3a,$85,$3c,$85,$40,$85,$42,$85,$40,$85,$3c,$85
@ref16:
	.byte $3a,$bd
	.byte $ff,$0f
	.word @ref15
@ref18:
	.byte $9a,$40,$85,$41,$41,$3a,$85,$00,$8d,$42,$85,$46,$85,$00,$85
@ref19:
	.byte $40,$85,$41,$41,$3a,$85,$00,$8d,$42,$85,$46,$85,$42,$85
@ref20:
	.byte $40,$85,$41,$41,$3a,$85,$00,$8d,$42,$85,$46,$85,$00,$85
	.byte $ff,$0e
	.word @ref19
	.byte $fd
	.word @song0ch0loop

@song0ch1:
@song0ch1loop:
@ref22:
	.byte $00,$83,$98,$40,$8d,$3a,$85,$32,$85,$42,$8d,$46,$85,$42
@ref23:
	.byte $85,$40,$8d,$3a,$85,$32,$85,$42,$8d,$46,$85,$42
@ref24:
	.byte $85,$4a,$8d,$40,$85,$3a,$85,$46,$85,$42,$85,$40,$85,$42
	.byte $ff,$0e
	.word @ref24
@ref26:
	.byte $9a,$40,$95,$40,$85,$42,$95,$42,$85
@ref27:
	.byte $40,$85,$3c,$8d,$3c,$85,$34,$85,$3c,$85,$4c,$8d
@ref28:
	.byte $4a,$9d,$4c,$9d
@ref29:
	.byte $4a,$9d,$46,$9d
@ref30:
	.byte $01,$32,$9d,$34,$99
@ref31:
	.byte $8b,$41,$42,$85,$46,$85,$4a,$85,$46,$85,$42,$85,$3c,$85
@ref32:
	.byte $83,$3a,$b9
	.byte $ff,$0f
	.word @ref15
@ref34:
	.byte $4b,$4b,$4f,$4b,$4b,$4f,$53,$55,$52,$8d,$4e,$85,$4a,$85
@ref35:
	.byte $87,$4a,$85,$52,$85,$58,$85,$4c,$85,$4c,$85,$54,$85,$5a,$85
@ref36:
	.byte $96,$3a,$95,$40,$8d,$34,$8d,$32,$85
@ref37:
	.byte $87,$42,$b5
@ref38:
	.byte $3a,$95,$40,$8d,$34,$8d,$32,$85
@ref39:
	.byte $87,$42,$b5
@ref40:
	.byte $9c,$59,$4b,$53,$55,$59,$4b,$53,$55,$59,$4b,$53,$55,$59,$4b,$53
	.byte $54,$81
@ref41:
	.byte $59,$4b,$53,$55,$59,$4b,$53,$55,$59,$4b,$53,$55,$59,$4b,$53,$54
	.byte $81
@ref42:
	.byte $5b,$4d,$55,$59,$5b,$4d,$55,$59,$5b,$4d,$55,$59,$5b,$4d,$55,$58
	.byte $81
@ref43:
	.byte $98,$46,$a7,$9a,$42,$85,$46,$85,$42,$83
	.byte $fd
	.word @song0ch1loop

@song0ch2:
@song0ch2loop:
@ref44:
	.byte $96,$32,$85,$32,$85,$3a,$85,$40,$85,$34,$85,$34,$85,$3c,$85,$42
	.byte $85
@ref45:
	.byte $32,$85,$32,$85,$3a,$85,$40,$85,$34,$85,$34,$85,$3c,$85,$42,$85
	.byte $ff,$10
	.word @ref45
	.byte $ff,$10
	.word @ref45
@ref48:
	.byte $1b,$32,$32,$33,$1b,$32,$32,$33,$1b,$32,$32,$25,$3c,$3c,$3d,$25
	.byte $3c,$3c,$3d,$25,$3c,$3c
@ref49:
	.byte $23,$3a,$3a,$3b,$23,$3a,$3a,$3b,$23,$3a,$3a,$1d,$1d,$35,$1d,$1d
	.byte $35,$21,$38,$81
	.byte $ff,$16
	.word @ref48
	.byte $ff,$14
	.word @ref49
@ref52:
	.byte $32,$85,$32,$85,$34,$85,$32,$85,$34,$85,$3a,$85,$34,$85,$32,$85
@ref53:
	.byte $32,$85,$32,$85,$34,$85,$32,$85,$34,$85,$3a,$85,$32,$85,$34,$85
@ref54:
	.byte $32,$8d,$34,$85,$32,$85,$34,$85,$3a,$85,$34,$85,$32,$83,$32
@ref55:
	.byte $22,$85,$3a,$3a,$3b,$22,$85,$3b,$3a,$3a,$1c,$85,$34,$34,$35,$1c
	.byte $85,$35,$34,$34
	.byte $ff,$10
	.word @ref52
	.byte $ff,$10
	.word @ref53
	.byte $ff,$0f
	.word @ref54
	.byte $ff,$14
	.word @ref55
@ref60:
	.byte $32,$8d,$34,$85,$32,$85,$34,$85,$3a,$8d,$23,$22,$22
@ref61:
	.byte $3a,$85,$52,$52,$53,$3a,$85,$53,$52,$52,$34,$85,$4c,$4c,$4d,$34
	.byte $85,$4d,$4c,$4c
@ref62:
	.byte $32,$85,$32,$85,$3a,$85,$3a,$85,$34,$85,$34,$85,$3c,$85,$34,$85
@ref63:
	.byte $32,$85,$32,$85,$3a,$85,$3a,$85,$34,$85,$34,$85,$3c,$85,$42,$85
	.byte $ff,$10
	.word @ref62
	.byte $ff,$10
	.word @ref63
	.byte $fd
	.word @song0ch2loop

@song0ch3:
@song0ch3loop:
@ref66:
	.byte $a0,$21,$a2,$1b,$a0,$21,$21,$9e,$21,$a2,$1b,$a0,$21,$a2,$1b,$a0
	.byte $21,$a2,$1b,$a0,$21,$21,$9e,$21,$a2,$1b,$a0,$21,$a2,$1a,$81
@ref67:
	.byte $a0,$20,$a2,$1a,$1e,$1a,$a0,$21,$21,$9e,$21,$a2,$1b,$a0,$21,$a2
	.byte $1b,$a0,$21,$a2,$1b,$a0,$21,$21,$9e,$21,$a0,$21,$9e,$21,$a0,$1a
	.byte $81
@ref68:
	.byte $21,$a2,$1b,$a0,$21,$21,$9e,$21,$a2,$1b,$a0,$21,$a2,$1b,$a0,$21
	.byte $a2,$1b,$a0,$21,$21,$9e,$21,$a2,$1b,$a0,$21,$a2,$1a,$81
	.byte $ff,$13
	.word @ref67
	.byte $ff,$11
	.word @ref68
	.byte $ff,$13
	.word @ref67
	.byte $ff,$11
	.word @ref68
	.byte $ff,$13
	.word @ref67
@ref74:
	.byte $21,$a2,$1b,$1f,$1b,$a0,$21,$a2,$1b,$1f,$1b,$a0,$21,$a2,$1b,$1f
	.byte $1b,$a0,$21,$a2,$1b,$a0,$21,$20,$81
@ref75:
	.byte $21,$1b,$a2,$1b,$1f,$a0,$21,$a2,$1a,$1e,$1a,$1e,$1b,$a0,$21,$a2
	.byte $1b,$1f,$1b,$a0,$21,$a2,$1b,$a0,$21,$20,$81
	.byte $ff,$11
	.word @ref74
	.byte $ff,$13
	.word @ref75
	.byte $ff,$11
	.word @ref74
	.byte $ff,$13
	.word @ref75
	.byte $ff,$11
	.word @ref74
	.byte $ff,$13
	.word @ref75
	.byte $ff,$11
	.word @ref74
	.byte $ff,$13
	.word @ref75
@ref84:
	.byte $21,$a2,$1b,$a0,$21,$a2,$1b,$9e,$21,$a2,$1b,$a0,$20,$a2,$1a,$a0
	.byte $21,$a2,$1b,$a0,$21,$21,$a2,$1b,$9e,$21,$a2,$1b,$1f,$1a,$81
@ref85:
	.byte $a0,$21,$a2,$1b,$a0,$21,$a2,$1b,$9e,$21,$a2,$1a,$1e,$a0,$20,$a2
	.byte $1a,$1e,$1a,$1f,$a0,$1b,$21,$a2,$1b,$9e,$21,$a0,$21,$9e,$21,$a0
	.byte $20,$81
	.byte $ff,$12
	.word @ref84
@ref87:
	.byte $a0,$21,$a2,$1b,$a0,$21,$a2,$1b,$9e,$21,$a2,$1b,$9e,$21,$1f,$21
	.byte $21,$1f,$1f,$03,$03,$21,$20,$81
	.byte $fd
	.word @song0ch3loop

@song0ch4:
@song0ch4loop:
@ref88:
	.byte $bf
@ref89:
	.byte $bf
@ref90:
	.byte $bf
@ref91:
	.byte $bf
@ref92:
	.byte $bf
@ref93:
	.byte $bf
@ref94:
	.byte $bf
@ref95:
	.byte $bf
@ref96:
	.byte $bf
@ref97:
	.byte $bf
@ref98:
	.byte $bf
@ref99:
	.byte $bf
@ref100:
	.byte $bf
@ref101:
	.byte $bf
@ref102:
	.byte $bf
@ref103:
	.byte $bf
@ref104:
	.byte $bf
@ref105:
	.byte $bf
@ref106:
	.byte $bf
@ref107:
	.byte $bf
@ref108:
	.byte $bf
@ref109:
	.byte $bf
	.byte $fd
	.word @song0ch4loop


@song1ch0:
	.byte $fb,$03
@song1ch0loop:
@ref110:
	.byte $01,$92,$2d,$01,$45,$01,$45,$01,$2d,$01,$2d,$00,$89,$45,$01,$2d
	.byte $00,$89,$3b,$01,$37,$01,$33,$01,$37,$01,$2d,$00,$85,$00,$85
@ref111:
	.byte $83,$2d,$01,$45,$01,$45,$01,$2d,$01,$2d,$00,$89,$45,$01,$2d,$00
	.byte $89,$3b,$01,$37,$01,$32,$85,$00,$99
@ref112:
	.byte $86,$2d,$01,$2d,$01,$2d,$01,$2d,$01,$2d,$01,$2d,$01,$2d,$01,$2d
	.byte $01,$31,$01,$31,$01,$31,$01,$31,$01,$31,$01,$31,$01,$31,$01,$31
	.byte $00,$81
@ref113:
	.byte $2d,$01,$2d,$01,$2d,$01,$2d,$01,$2d,$01,$2d,$01,$2d,$01,$2d,$01
	.byte $31,$01,$31,$01,$31,$01,$31,$01,$31,$01,$31,$01,$31,$01,$31,$00
	.byte $81
	.byte $ff,$21
	.word @ref113
	.byte $ff,$21
	.word @ref113
	.byte $ff,$21
	.word @ref113
	.byte $ff,$21
	.word @ref113
@ref118:
	.byte $84,$3c,$85,$92,$4a,$85,$84,$3a,$85,$92,$44,$85,$84,$36,$85,$92
	.byte $4e,$85,$84,$32,$89,$92,$4f,$84,$37,$01,$36,$85,$92,$4e,$85,$84
	.byte $3a,$85,$92,$4e,$85,$84,$36,$89,$01,$36,$85
@ref119:
	.byte $3c,$85,$92,$4a,$85,$84,$3a,$85,$92,$44,$85,$84,$36,$85,$92,$4e
	.byte $85,$84,$32,$89,$92,$4f,$84,$37,$01,$36,$85,$92,$4e,$85,$84,$3a
	.byte $85,$92,$4e,$85,$84,$36,$89,$01,$36,$85
	.byte $ff,$1e
	.word @ref119
	.byte $ff,$1e
	.word @ref119
@ref122:
	.byte $14,$85,$22,$85,$30,$85,$32,$8d,$90,$40,$ad,$00,$85,$92,$2c,$85
	.byte $32,$85,$2c,$85,$32,$85
@ref123:
	.byte $32,$85,$2c,$85,$00,$cd,$84,$14,$85,$22,$85,$30,$85,$32,$85
@ref124:
	.byte $87,$90,$40,$b5,$92,$2c,$85,$32,$85,$2c,$85,$32,$85,$32,$85,$2c
	.byte $85,$00,$8d
@ref125:
	.byte $df
	.byte $ff,$1e
	.word @ref118
	.byte $ff,$1e
	.word @ref119
	.byte $ff,$1e
	.word @ref119
	.byte $ff,$1e
	.word @ref119
	.byte $ff,$1e
	.word @ref119
	.byte $ff,$1e
	.word @ref119
	.byte $ff,$1e
	.word @ref119
	.byte $ff,$1e
	.word @ref119
	.byte $fd
	.word @song1ch0loop

@song1ch1:
@song1ch1loop:
@ref134:
	.byte $90,$2d,$01,$45,$01,$45,$01,$2d,$01,$2d,$00,$89,$45,$01,$2d,$00
	.byte $89,$3b,$01,$37,$01,$33,$01,$37,$01,$2d,$01,$2c,$89,$00,$81
@ref135:
	.byte $2d,$01,$45,$01,$45,$01,$2d,$01,$2d,$00,$89,$45,$01,$2d,$00,$89
	.byte $3b,$01,$37,$01,$32,$85,$00,$9d
@ref136:
	.byte $2d,$01,$45,$01,$45,$01,$2d,$01,$2d,$00,$89,$45,$01,$2d,$00,$89
	.byte $3b,$01,$37,$01,$33,$01,$37,$01,$2d,$01,$2c,$89,$00,$81
	.byte $ff,$18
	.word @ref135
	.byte $ff,$1e
	.word @ref136
	.byte $ff,$18
	.word @ref135
	.byte $ff,$1e
	.word @ref136
	.byte $ff,$18
	.word @ref135
@ref142:
	.byte $4a,$85,$4a,$85,$44,$85,$4a,$85,$4f,$01,$4e,$89,$01,$4e,$85,$00
	.byte $85,$4e,$85,$52,$85,$4e,$85,$4a,$85,$00,$95
	.byte $ff,$1b
	.word @ref142
	.byte $ff,$1b
	.word @ref142
	.byte $ff,$1b
	.word @ref142
@ref146:
	.byte $94,$32,$85,$2d,$01,$2d,$01,$29,$01,$2d,$01,$2d,$01,$92,$40,$a5
	.byte $90,$2c,$85,$32,$85,$2c,$85,$32,$85,$32,$85
@ref147:
	.byte $2c,$85,$00,$d5,$94,$32,$85,$2d,$01,$2d,$01,$29,$00,$81
@ref148:
	.byte $2d,$01,$2d,$01,$92,$40,$a5,$90,$2c,$85,$32,$85,$2c,$85,$32,$85
	.byte $32,$85,$2c,$85,$00,$95
@ref149:
	.byte $df
	.byte $ff,$1b
	.word @ref142
	.byte $ff,$1b
	.word @ref142
	.byte $ff,$1b
	.word @ref142
	.byte $ff,$1b
	.word @ref142
	.byte $ff,$1b
	.word @ref142
	.byte $ff,$1b
	.word @ref142
	.byte $ff,$1b
	.word @ref142
	.byte $ff,$1b
	.word @ref142
	.byte $fd
	.word @song1ch1loop

@song1ch2:
@song1ch2loop:
@ref158:
	.byte $00,$f9,$83
@ref159:
	.byte $df,$8e,$4a,$95,$00,$85
@ref160:
	.byte $f9,$85
@ref161:
	.byte $f9,$85
@ref162:
	.byte $84,$45,$01,$44,$85,$48,$85,$00,$85,$4a,$85,$00,$9d,$4e,$85,$40
	.byte $85,$00,$85,$40,$85,$00,$95
@ref163:
	.byte $45,$01,$44,$85,$48,$85,$00,$85,$4a,$85,$00,$85,$80,$4c,$85,$4e
	.byte $85,$00,$85,$40,$85,$00,$85,$40,$85,$00,$9d
	.byte $ff,$16
	.word @ref162
	.byte $ff,$1a
	.word @ref163
@ref166:
	.byte $3c,$85,$24,$85,$28,$89,$01,$2c,$89,$00,$99,$36,$85,$28,$89,$01
	.byte $28,$89,$00,$91
@ref167:
	.byte $3c,$85,$24,$85,$28,$89,$01,$2c,$89,$01,$36,$89,$01,$29,$01,$28
	.byte $85,$2c,$89,$01,$30,$85,$32,$85,$34,$85,$36,$85
	.byte $ff,$14
	.word @ref166
	.byte $ff,$1c
	.word @ref167
@ref170:
	.byte $2d,$01,$2d,$01,$2d,$01,$2d,$01,$2d,$01,$2d,$01,$2d,$01,$2d,$01
	.byte $2d,$01,$2d,$01,$2d,$01,$2d,$01,$2d,$01,$2d,$01,$2d,$01,$2d,$00
	.byte $81
	.byte $ff,$21
	.word @ref170
	.byte $ff,$21
	.word @ref170
@ref173:
	.byte $2d,$01,$2d,$01,$2d,$01,$2d,$01,$2d,$01,$2d,$01,$2d,$01,$2d,$01
	.byte $8e,$45,$45,$5d,$45,$45,$5d,$45,$5c,$81
@ref174:
	.byte $80,$3c,$85,$24,$85,$28,$89,$01,$2c,$89,$00,$99,$36,$85,$28,$89
	.byte $01,$28,$89,$00,$91
	.byte $ff,$1c
	.word @ref167
	.byte $ff,$14
	.word @ref166
	.byte $ff,$1c
	.word @ref167
	.byte $ff,$14
	.word @ref166
	.byte $ff,$1c
	.word @ref167
	.byte $ff,$14
	.word @ref166
	.byte $ff,$1c
	.word @ref167
	.byte $fd
	.word @song1ch2loop

@song1ch3:
@song1ch3loop:
@ref182:
	.byte $f9,$85
@ref183:
	.byte $f9,$85
@ref184:
	.byte $8a,$21,$8c,$1b,$8a,$21,$8c,$1b,$88,$21,$8c,$1b,$1b,$1b,$8a,$21
	.byte $8c,$1b,$8a,$21,$8c,$1b,$88,$21,$8c,$1b,$1b,$1b,$8a,$21,$8c,$1b
	.byte $8a,$21,$8c,$1b,$88,$21,$8c,$1b,$1b,$1b,$8a,$21,$8c,$1b,$8a,$21
	.byte $8c,$1b,$88,$21,$8c,$1b,$1b,$1a,$81
	.byte $ff,$21
	.word @ref184
	.byte $ff,$21
	.word @ref184
	.byte $ff,$21
	.word @ref184
	.byte $ff,$21
	.word @ref184
@ref189:
	.byte $8a,$21,$8c,$1b,$8a,$21,$8c,$1b,$88,$21,$8c,$1b,$1b,$1b,$8a,$21
	.byte $8c,$1b,$8a,$21,$8c,$1b,$88,$21,$8c,$1b,$1b,$1b,$8a,$21,$8c,$1b
	.byte $8a,$21,$8c,$1b,$88,$21,$8c,$1b,$1b,$1b,$88,$21,$21,$21,$21,$8a
	.byte $21,$21,$88,$21,$20,$81
	.byte $ff,$21
	.word @ref184
	.byte $ff,$21
	.word @ref184
	.byte $ff,$21
	.word @ref184
	.byte $ff,$21
	.word @ref184
	.byte $ff,$21
	.word @ref184
	.byte $ff,$21
	.word @ref184
	.byte $ff,$21
	.word @ref184
@ref197:
	.byte $8a,$21,$8c,$1b,$8a,$21,$8c,$1b,$88,$21,$8c,$1b,$1b,$1b,$8a,$21
	.byte $8c,$1b,$8a,$21,$8c,$1b,$88,$21,$8c,$1b,$1b,$1b,$8a,$21,$8c,$1b
	.byte $8a,$21,$8c,$1b,$88,$21,$8c,$1b,$1b,$1a,$81
	.byte $ff,$21
	.word @ref184
	.byte $ff,$21
	.word @ref184
	.byte $ff,$21
	.word @ref184
	.byte $ff,$21
	.word @ref184
	.byte $ff,$21
	.word @ref184
	.byte $ff,$21
	.word @ref184
	.byte $ff,$21
	.word @ref184
	.byte $ff,$21
	.word @ref189
	.byte $fd
	.word @song1ch3loop

@song1ch4:
@song1ch4loop:
@ref206:
	.byte $f9,$85
@ref207:
	.byte $f9,$85
@ref208:
	.byte $f9,$85
@ref209:
	.byte $f9,$85
@ref210:
	.byte $f9,$85
@ref211:
	.byte $f9,$85
@ref212:
	.byte $f9,$85
@ref213:
	.byte $f9,$85
@ref214:
	.byte $f9,$85
@ref215:
	.byte $f9,$85
@ref216:
	.byte $f9,$85
@ref217:
	.byte $f9,$85
@ref218:
	.byte $f9,$85
@ref219:
	.byte $f9,$85
@ref220:
	.byte $f9,$85
@ref221:
	.byte $df
@ref222:
	.byte $f9,$85
@ref223:
	.byte $f9,$85
@ref224:
	.byte $f9,$85
@ref225:
	.byte $f9,$85
@ref226:
	.byte $f9,$85
@ref227:
	.byte $f9,$85
@ref228:
	.byte $f9,$85
@ref229:
	.byte $f9,$85
	.byte $fd
	.word @song1ch4loop


@song2ch0:
	.byte $fb,$03
@ref230:
	.byte $9a,$32,$85,$32,$85,$32,$85,$36,$95,$32,$85,$32,$85,$32,$85,$36
	.byte $8d,$9c,$3a,$85,$9a,$32,$85,$36,$85,$3a,$85,$32,$85
@ref231:
	.byte $40,$85,$3c,$85,$3a,$85,$32,$85,$40,$85,$3c,$85,$3c,$85,$3a,$8d
	.byte $32,$b5
@ref232:
	.byte $8f
@song2ch0loop:
@ref233:
	.byte $00
	.byte $fd
	.word @song2ch0loop

@song2ch1:
@ref234:
	.byte $9c,$58,$85,$58,$8d,$54,$8d,$54,$85,$52,$85,$4a,$a5,$4a,$85,$4e
	.byte $85,$52,$85,$4a,$85
@ref235:
	.byte $58,$8d,$52,$85,$98,$32,$e5
@ref236:
	.byte $8f
@song2ch1loop:
@ref237:
	.byte $00
	.byte $fd
	.word @song2ch1loop

@song2ch2:
@ref238:
	.byte $96,$32,$85,$32,$85,$32,$85,$36,$85,$36,$85,$36,$85,$32,$85,$32
	.byte $85,$32,$85,$36,$85,$36,$85,$36,$85,$32,$85,$36,$85,$3a,$85,$32
	.byte $85
@ref239:
	.byte $40,$85,$3c,$85,$3a,$85,$32,$ad,$32,$b5
@ref240:
	.byte $8f
@song2ch2loop:
@ref241:
	.byte $00
	.byte $fd
	.word @song2ch2loop

@song2ch3:
@ref242:
	.byte $a0,$21,$a2,$1b,$a0,$21,$a2,$1b,$9e,$21,$a2,$1b,$a0,$21,$a2,$1b
	.byte $a0,$21,$21,$9e,$21,$a2,$1b,$a0,$21,$a2,$1b,$a0,$21,$a2,$1b,$9e
	.byte $21,$a2,$1b,$a0,$21,$a2,$1b,$a0,$21,$a2,$1b,$a0,$21,$a2,$1b,$9e
	.byte $21,$21,$1f,$1f,$03,$03,$21,$20,$81
@ref243:
	.byte $20,$85,$20,$85,$21,$21,$20,$e5
@ref244:
	.byte $8f
@song2ch3loop:
@ref245:
	.byte $00
	.byte $fd
	.word @song2ch3loop

@song2ch4:
@ref246:
	.byte $f9,$85
@ref247:
	.byte $f9,$85
@ref248:
	.byte $8f
@song2ch4loop:
@ref249:
	.byte $81
	.byte $fd
	.word @song2ch4loop
