;this file for FamiTone2 library generated by text2data tool

music_music_data:
	.byte 1
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256

@instruments:
	.byte $30 ;instrument $00
	.word @env2,@env0,@env0
	.byte $00
	.byte $30 ;instrument $01
	.word @env1,@env0,@env10
	.byte $00
	.byte $70 ;instrument $02
	.word @env3,@env0,@env0
	.byte $00
	.byte $30 ;instrument $03
	.word @env4,@env8,@env0
	.byte $00
	.byte $30 ;instrument $04
	.word @env5,@env9,@env0
	.byte $00
	.byte $30 ;instrument $05
	.word @env7,@env0,@env0
	.byte $00
	.byte $30 ;instrument $06
	.word @env6,@env0,@env0
	.byte $00

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $c1,$c3,$c7,$c9,$00,$03
@env2:
	.byte $ce,$00,$00
@env3:
	.byte $ca,$07,$c7,$05,$ca,$07,$ca,$00,$06
@env4:
	.byte $c8,$00,$00
@env5:
	.byte $cd,$cb,$c9,$c8,$c5,$c3,$c1,$c0,$00,$07
@env6:
	.byte $c7,$c2,$c0,$00,$02
@env7:
	.byte $cc,$ca,$c8,$c6,$c4,$c3,$c2,$c1,$c0,$00,$08
@env8:
	.byte $cc,$c0,$00,$01
@env9:
	.byte $c7,$c3,$c0,$bd,$00,$02
@env10:
	.byte $c0,$0e,$bf,$be,$bd,$bc,$bd,$be,$bf,$c0,$00,$02


@song0ch0:
	.byte $fb,$05
@song0ch0loop:
@ref0:
	.byte $86,$53,$01,$53,$01,$53,$01,$53,$00,$81
@ref1:
	.byte $53,$01,$53,$01,$53,$01,$53,$00,$81
	.byte $ff,$09
	.word @ref1
	.byte $ff,$09
	.word @ref1
@ref4:
	.byte $00,$85,$5b,$5b,$5b,$5b,$56,$85
@ref5:
	.byte $57,$57,$53,$53,$50,$85,$56,$85
@ref6:
	.byte $00,$8d,$82,$56,$89,$00,$81
@ref7:
	.byte $51,$01,$48,$8d,$44,$85
@ref8:
	.byte $87,$86,$57,$57,$57,$57,$52,$85
@ref9:
	.byte $52,$85,$51,$51,$4c,$85,$50,$85
@ref10:
	.byte $00,$8d,$82,$52,$89,$00,$81
@ref11:
	.byte $49,$01,$44,$8d,$42,$85
@ref12:
	.byte $00,$85,$86,$5b,$5b,$5b,$5b,$56,$85
	.byte $ff,$08
	.word @ref5
	.byte $ff,$06
	.word @ref6
	.byte $ff,$06
	.word @ref7
	.byte $ff,$07
	.word @ref8
	.byte $ff,$08
	.word @ref9
	.byte $ff,$06
	.word @ref10
@ref19:
	.byte $49,$01,$3a,$85,$3e,$85,$3a,$85
@ref20:
	.byte $4c,$89,$01,$45,$01,$3a,$85
@ref21:
	.byte $9f
@ref22:
	.byte $40,$85,$46,$85,$4c,$85,$52,$85
@ref23:
	.byte $87,$4c,$85,$52,$85,$4c,$85
@ref24:
	.byte $52,$83,$00,$52,$95
@ref25:
	.byte $9f
@ref26:
	.byte $86,$52,$85,$4c,$85,$48,$85,$4c,$85
@ref27:
	.byte $8f,$4c,$85,$50,$85
@ref28:
	.byte $52,$85,$51,$4c,$85,$51,$53,$50,$81
@ref29:
	.byte $4c,$9d
	.byte $ff,$09
	.word @ref28
@ref31:
	.byte $4c,$83,$00,$84,$4c,$85,$48,$85,$52,$85
	.byte $fd
	.word @song0ch0loop

@song0ch1:
@song0ch1loop:
@ref32:
	.byte $86,$49,$01,$49,$01,$49,$01,$49,$00,$81
@ref33:
	.byte $49,$01,$49,$01,$49,$01,$49,$00,$81
	.byte $ff,$09
	.word @ref33
	.byte $ff,$09
	.word @ref33
@ref36:
	.byte $00,$85,$53,$53,$53,$53,$50,$85
@ref37:
	.byte $51,$51,$4d,$4d,$48,$85,$50,$85
	.byte $ff,$09
	.word @ref33
	.byte $ff,$09
	.word @ref33
@ref40:
	.byte $49,$01,$51,$51,$51,$51,$4c,$85
@ref41:
	.byte $4c,$85,$49,$49,$46,$85,$49,$42,$81
	.byte $ff,$09
	.word @ref33
	.byte $ff,$09
	.word @ref33
	.byte $ff,$08
	.word @ref36
	.byte $ff,$08
	.word @ref37
	.byte $ff,$09
	.word @ref33
	.byte $ff,$09
	.word @ref33
	.byte $ff,$08
	.word @ref40
	.byte $ff,$09
	.word @ref41
@ref50:
	.byte $83,$01,$49,$01,$49,$01,$49,$00,$81
	.byte $ff,$09
	.word @ref33
@ref52:
	.byte $84,$34,$89,$01,$2d,$01,$22,$85
@ref53:
	.byte $9f
	.byte $ff,$08
	.word @ref22
@ref55:
	.byte $87,$34,$85,$3a,$85,$34,$85
@ref56:
	.byte $3a,$83,$00,$3a,$95
@ref57:
	.byte $9f
@ref58:
	.byte $86,$4d,$01,$4d,$01,$4d,$01,$4d,$00,$81
@ref59:
	.byte $4d,$01,$4d,$01,$4d,$01,$4d,$00,$81
@ref60:
	.byte $46,$85,$00,$85,$46,$85,$00,$85
@ref61:
	.byte $47,$01,$47,$01,$47,$00,$89
@ref62:
	.byte $4c,$85,$00,$85,$4c,$85,$00,$85
@ref63:
	.byte $4d,$01,$4d,$01,$4d,$00,$89
	.byte $fd
	.word @song0ch1loop

@song0ch2:
@song0ch2loop:
@ref64:
	.byte $80,$3a,$85,$00,$85,$30,$85,$00,$85
@ref65:
	.byte $3b,$01,$30,$85,$34,$85,$38,$85
@ref66:
	.byte $3a,$85,$00,$85,$30,$85,$00,$85
	.byte $ff,$08
	.word @ref65
@ref68:
	.byte $00,$9d
@ref69:
	.byte $9f
@ref70:
	.byte $30,$85,$00,$85,$3e,$85,$00,$85
	.byte $ff,$08
	.word @ref70
	.byte $ff,$08
	.word @ref70
@ref73:
	.byte $30,$85,$00,$85,$3e,$85,$30,$85
	.byte $ff,$08
	.word @ref66
	.byte $ff,$08
	.word @ref65
	.byte $ff,$08
	.word @ref66
	.byte $ff,$08
	.word @ref66
	.byte $ff,$08
	.word @ref70
	.byte $ff,$08
	.word @ref70
	.byte $ff,$08
	.word @ref70
	.byte $ff,$08
	.word @ref73
	.byte $ff,$08
	.word @ref66
@ref83:
	.byte $3b,$01,$3b,$01,$3e,$85,$42,$85
@ref84:
	.byte $44,$85,$00,$85,$3a,$85,$00,$85
	.byte $ff,$08
	.word @ref84
@ref86:
	.byte $28,$85,$2e,$85,$34,$85,$3a,$85
@ref87:
	.byte $87,$2e,$85,$34,$85,$3a,$85
	.byte $ff,$08
	.word @ref66
@ref89:
	.byte $3a,$85,$00,$85,$3b,$01,$38,$85
@ref90:
	.byte $34,$85,$00,$85,$2a,$85,$00,$85
@ref91:
	.byte $34,$85,$00,$85,$42,$85,$00,$85
@ref92:
	.byte $3e,$85,$00,$85,$34,$85,$00,$85
@ref93:
	.byte $3f,$01,$3f,$01,$3e,$8d
	.byte $ff,$08
	.word @ref84
@ref95:
	.byte $45,$01,$45,$01,$44,$8d
	.byte $fd
	.word @song0ch2loop

@song0ch3:
@song0ch3loop:
@ref96:
	.byte $8a,$21,$8c,$1b,$88,$21,$8c,$1b,$8a,$21,$8c,$1b,$88,$21,$8c,$1a
	.byte $81
@ref97:
	.byte $8a,$21,$8c,$1b,$88,$21,$8c,$1b,$8a,$21,$8c,$1b,$88,$21,$8a,$20
	.byte $81
@ref98:
	.byte $21,$8c,$1b,$88,$21,$8c,$1b,$8a,$21,$8c,$1b,$88,$21,$8c,$1a,$81
	.byte $ff,$09
	.word @ref97
@ref100:
	.byte $88,$20,$85,$8c,$1a,$85,$1a,$85,$1a,$85
@ref101:
	.byte $1b,$1b,$16,$85,$1b,$1b,$16,$85
	.byte $ff,$09
	.word @ref96
	.byte $ff,$09
	.word @ref97
	.byte $ff,$09
	.word @ref98
	.byte $ff,$09
	.word @ref97
	.byte $ff,$09
	.word @ref98
	.byte $ff,$09
	.word @ref97
	.byte $ff,$09
	.word @ref98
	.byte $ff,$09
	.word @ref97
	.byte $ff,$09
	.word @ref98
	.byte $ff,$09
	.word @ref97
	.byte $ff,$09
	.word @ref98
	.byte $ff,$09
	.word @ref97
	.byte $ff,$09
	.word @ref98
@ref115:
	.byte $8a,$21,$8c,$1b,$88,$21,$8c,$1b,$88,$21,$8c,$1b,$88,$21,$20,$81
	.byte $ff,$09
	.word @ref96
	.byte $ff,$09
	.word @ref97
@ref118:
	.byte $88,$21,$8c,$1b,$88,$21,$8c,$1b,$88,$21,$21,$21,$8c,$1a,$81
@ref119:
	.byte $8a,$21,$21,$88,$21,$8c,$1b,$8a,$21,$8c,$1b,$88,$21,$8a,$20,$81
	.byte $ff,$09
	.word @ref98
	.byte $ff,$09
	.word @ref97
	.byte $ff,$09
	.word @ref98
	.byte $ff,$09
	.word @ref97
	.byte $ff,$09
	.word @ref98
	.byte $ff,$09
	.word @ref115
	.byte $ff,$09
	.word @ref96
	.byte $ff,$09
	.word @ref115
	.byte $fd
	.word @song0ch3loop

@song0ch4:
@song0ch4loop:
@ref128:
	.byte $9f
@ref129:
	.byte $9f
@ref130:
	.byte $9f
@ref131:
	.byte $9f
@ref132:
	.byte $9f
@ref133:
	.byte $9f
@ref134:
	.byte $9f
@ref135:
	.byte $9f
@ref136:
	.byte $9f
@ref137:
	.byte $9f
@ref138:
	.byte $9f
@ref139:
	.byte $9f
@ref140:
	.byte $9f
@ref141:
	.byte $9f
@ref142:
	.byte $9f
@ref143:
	.byte $9f
@ref144:
	.byte $9f
@ref145:
	.byte $9f
@ref146:
	.byte $9f
@ref147:
	.byte $9f
@ref148:
	.byte $9f
@ref149:
	.byte $9f
@ref150:
	.byte $9f
@ref151:
	.byte $9f
@ref152:
	.byte $9f
@ref153:
	.byte $9f
@ref154:
	.byte $9f
@ref155:
	.byte $9f
@ref156:
	.byte $9f
@ref157:
	.byte $9f
@ref158:
	.byte $9f
@ref159:
	.byte $9f
	.byte $fd
	.word @song0ch4loop
