// Patterns, tiles, metatiles, and maybe dragons. Generated by mkts
// Copyleft 2017 The Mojon Twins

// Tileset tilemaps & pals generated by mkts [nes mode]
// Copyleft 2017 The Mojon Twins
 
const unsigned char texts2_pals [] = {
	0x01, 0x03, 
	0x00, 0x00
};

const unsigned char texts2_tmaps [] = {
	0xa7, 0xa8, 0xa9, 0xaa, 
	0xab, 0x00, 0xab, 0x00, 
	0xac, 0xad, 0xae, 0xaf, 
	0x00, 0x00, 0x00, 0x00
};

