;this file for FamiTone2 library generated by text2data tool

music_music_data:
	.byte 2
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256
	.word @song1ch0,@song1ch1,@song1ch2,@song1ch3,@song1ch4,307,256

@instruments:
	.byte $30 ;instrument $00
	.word @env2,@env0,@env0
	.byte $00
	.byte $30 ;instrument $01
	.word @env1,@env0,@env16
	.byte $00
	.byte $30 ;instrument $04
	.word @env5,@env15,@env0
	.byte $00
	.byte $30 ;instrument $05
	.word @env9,@env0,@env0
	.byte $00
	.byte $30 ;instrument $06
	.word @env6,@env0,@env0
	.byte $00
	.byte $30 ;instrument $07
	.word @env1,@env14,@env0
	.byte $00
	.byte $70 ;instrument $08
	.word @env3,@env0,@env17
	.byte $00
	.byte $70 ;instrument $09
	.word @env4,@env0,@env17
	.byte $00
	.byte $30 ;instrument $0a
	.word @env3,@env0,@env17
	.byte $00
	.byte $30 ;instrument $0e
	.word @env8,@env0,@env0
	.byte $00
	.byte $30 ;instrument $0f
	.word @env7,@env0,@env16
	.byte $00
	.byte $70 ;instrument $10
	.word @env10,@env0,@env0
	.byte $00
	.byte $30 ;instrument $12
	.word @env11,@env15,@env0
	.byte $00
	.byte $30 ;instrument $13
	.word @env13,@env0,@env0
	.byte $00
	.byte $30 ;instrument $14
	.word @env12,@env0,@env0
	.byte $00

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $ca,$00,$00
@env2:
	.byte $cf,$00,$00
@env3:
	.byte $cc,$cb,$ca,$ca,$c9,$03,$c8,$03,$c7,$07,$c6,$08,$c5,$0a,$c4,$0c
	.byte $c3,$0c,$c2,$12,$c1,$19,$c0,$00,$16
@env4:
	.byte $c4,$02,$c3,$0c,$c2,$0b,$c1,$12,$c0,$00,$08
@env5:
	.byte $c7,$c4,$c2,$c1,$c0,$00,$04
@env6:
	.byte $c7,$c2,$c0,$00,$02
@env7:
	.byte $c1,$c3,$c7,$c9,$00,$03
@env8:
	.byte $ce,$00,$00
@env9:
	.byte $c8,$c6,$c4,$c2,$c0,$00,$04
@env10:
	.byte $c9,$08,$c6,$05,$c9,$06,$c9,$00,$06
@env11:
	.byte $ce,$cc,$ca,$c8,$c6,$c4,$c2,$c1,$c0,$00,$08
@env12:
	.byte $ca,$c5,$c3,$c2,$c0,$00,$04
@env13:
	.byte $cc,$cb,$c9,$c8,$c6,$c5,$c3,$c2,$c0,$00,$08
@env14:
	.byte $c0,$05,$bf,$be,$bd,$bc,$bb,$ba,$b9,$b8,$b7,$b6,$b5,$b4,$b3,$b2
	.byte $b1,$b0,$af,$ae,$ad,$ac,$ab,$aa,$a9,$a8,$a8,$a7,$a7,$a6,$a6,$a5
	.byte $a5,$a4,$a4,$a3,$a3,$a2,$a2,$a1,$a1,$00,$28
@env15:
	.byte $c7,$c3,$c0,$bd,$00,$02
@env16:
	.byte $c0,$0e,$bf,$be,$bd,$bc,$bd,$be,$bf,$c0,$00,$02
@env17:
	.byte $c0,$0f,$c1,$02,$c2,$02,$c1,$02,$c0,$c0,$c0,$00,$02


@song0ch0:
	.byte $fb,$05
@ref0:
	.byte $01,$8e,$3b,$00,$89,$49,$00,$85,$37,$01,$37,$00,$85,$49,$00,$85
	.byte $37,$33,$00,$89,$49,$00,$85,$37,$01,$37,$00,$85,$49,$01,$40,$81
@ref1:
	.byte $01,$3b,$00,$89,$49,$00,$85,$37,$01,$37,$00,$85,$49,$00,$85,$37
	.byte $33,$00,$89,$49,$00,$85,$37,$01,$37,$00,$85,$49,$01,$40,$81
@song0ch0loop:
	.byte $ff,$1f
	.word @ref0
	.byte $ff,$1f
	.word @ref1
@ref4:
	.byte $82,$23,$00,$89,$31,$00,$85,$1f,$01,$1f,$00,$85,$31,$00,$85,$1f
	.byte $1b,$00,$89,$31,$00,$85,$1f,$01,$1f,$00,$85,$31,$01,$29,$2c,$81
@ref5:
	.byte $23,$00,$89,$31,$00,$85,$1f,$01,$1f,$00,$85,$31,$00,$85,$1f,$1b
	.byte $00,$89,$31,$00,$85,$1f,$01,$1f,$00,$85,$31,$01,$29,$2c,$81
	.byte $ff,$1f
	.word @ref5
	.byte $ff,$1f
	.word @ref5
	.byte $ff,$1f
	.word @ref5
	.byte $ff,$1f
	.word @ref5
@ref10:
	.byte $00,$85,$8e,$3a,$95,$36,$95,$36,$85,$36,$85,$3a,$95,$40,$8d,$3e
	.byte $85,$3a,$85
@ref11:
	.byte $00,$85,$3a,$95,$36,$95,$36,$85,$36,$85,$3a,$95,$40,$8d,$3e,$85
	.byte $3a,$85
@ref12:
	.byte $8c,$52,$85,$58,$85,$52,$85,$4e,$85,$36,$85,$4e,$85,$36,$85,$44
	.byte $85,$4a,$85,$4a,$85,$40,$85,$4a,$8d,$4e,$85,$52,$85,$4e,$85
@ref13:
	.byte $52,$85,$58,$85,$52,$85,$4e,$85,$36,$85,$4e,$85,$36,$85,$44,$85
	.byte $4a,$85,$4a,$85,$40,$85,$4a,$8d,$4e,$85,$52,$85,$4e,$85
@ref14:
	.byte $87,$8e,$3a,$85,$3a,$85,$41,$3a,$89,$36,$85,$3a,$85,$36,$85,$40
	.byte $8d,$3a,$85,$3a,$85,$36,$8d,$3a,$8d
@ref15:
	.byte $3a,$85,$44,$85,$48,$85,$44,$85,$3b,$44,$89,$48,$85,$44,$85,$36
	.byte $85,$44,$85,$48,$85,$44,$85,$37,$44,$89,$48,$85,$44,$85
	.byte $fd
	.word @song0ch0loop

@song0ch1:
@ref16:
	.byte $8c,$3b,$00,$89,$49,$00,$85,$37,$01,$37,$00,$85,$49,$00,$85,$37
	.byte $33,$00,$89,$49,$00,$85,$37,$01,$37,$00,$85,$49,$01,$41,$44,$81
@ref17:
	.byte $3b,$00,$89,$49,$00,$85,$37,$01,$37,$00,$85,$49,$00,$85,$37,$33
	.byte $00,$89,$49,$00,$85,$37,$01,$37,$00,$85,$49,$01,$41,$44,$81
@song0ch1loop:
	.byte $ff,$1f
	.word @ref16
	.byte $ff,$1f
	.word @ref17
	.byte $ff,$1f
	.word @ref17
	.byte $ff,$1f
	.word @ref17
@ref22:
	.byte $53,$01,$53,$01,$53,$4f,$01,$59,$01,$59,$00,$85,$53,$01,$4e,$00
	.byte $4e,$00,$59,$01,$53,$01,$59,$59,$01,$59,$01,$59,$00,$85,$59,$01
	.byte $4f,$52,$81
	.byte $ff,$23
	.word @ref22
	.byte $ff,$1f
	.word @ref17
	.byte $ff,$1f
	.word @ref17
@ref26:
	.byte $3a,$95,$36,$95,$36,$85,$36,$85,$3a,$95,$40,$8d,$3e,$85,$3a,$85
	.byte $36,$85
	.byte $ff,$12
	.word @ref26
	.byte $ff,$12
	.word @ref26
	.byte $ff,$12
	.word @ref26
@ref30:
	.byte $3a,$85,$3a,$85,$41,$3a,$89,$36,$85,$3a,$85,$36,$85,$40,$8d,$3a
	.byte $85,$3a,$85,$36,$8d,$3a,$95
@ref31:
	.byte $3a,$85,$3a,$85,$41,$3a,$89,$36,$85,$3a,$85,$36,$85,$40,$8d,$3a
	.byte $85,$3a,$85,$44,$8d,$48,$95
	.byte $fd
	.word @song0ch1loop

@song0ch2:
@ref32:
	.byte $f9,$85
@ref33:
	.byte $f9,$85
@song0ch2loop:
@ref34:
	.byte $80,$22,$89,$23,$3a,$85,$23,$23,$1e,$89,$1f,$36,$85,$1f,$1f,$1a
	.byte $89,$1b,$32,$85,$8a,$33,$33,$37,$37,$4f,$37,$37,$4f,$37,$4e,$81
	.byte $ff,$1e
	.word @ref34
@ref36:
	.byte $80,$3b,$00,$89,$3b,$37,$01,$3b,$01,$3b,$00,$85,$3b,$01,$37,$01
	.byte $3b,$00,$89,$3b,$37,$01,$3b,$01,$3b,$00,$85,$3b,$01,$41,$00,$81
@ref37:
	.byte $3b,$00,$89,$3b,$37,$01,$3b,$01,$3b,$00,$85,$3b,$01,$37,$01,$3b
	.byte $00,$89,$3b,$37,$01,$3b,$01,$3b,$00,$85,$3b,$01,$41,$00,$81
@ref38:
	.byte $3b,$00,$89,$3b,$37,$01,$37,$01,$49,$00,$85,$41,$01,$37,$01,$3b
	.byte $00,$89,$3b,$3b,$01,$49,$01,$49,$00,$85,$3b,$01,$41,$00,$81
	.byte $ff,$1f
	.word @ref38
	.byte $ff,$1f
	.word @ref37
	.byte $ff,$1f
	.word @ref37
@ref42:
	.byte $3b,$01,$3b,$01,$3b,$01,$3b,$53,$37,$01,$37,$01,$37,$01,$37,$4f
	.byte $33,$01,$33,$01,$33,$01,$33,$4b,$37,$01,$37,$01,$37,$01,$37,$4e
	.byte $81
	.byte $ff,$21
	.word @ref42
	.byte $ff,$21
	.word @ref42
	.byte $ff,$21
	.word @ref42
	.byte $ff,$21
	.word @ref42
@ref47:
	.byte $3b,$52,$85,$3b,$52,$85,$3b,$3b,$37,$4e,$85,$37,$4e,$85,$37,$37
	.byte $33,$4a,$85,$33,$4a,$85,$8a,$4b,$4b,$4f,$4f,$67,$4f,$4f,$67,$4f
	.byte $66,$81
	.byte $fd
	.word @song0ch2loop

@song0ch3:
@ref48:
	.byte $f9,$85
@ref49:
	.byte $f9,$85
@song0ch3loop:
@ref50:
	.byte $d7,$88,$1b,$1b,$84,$21,$21,$86,$21,$21,$84,$21,$21,$21,$20,$81
@ref51:
	.byte $86,$21,$21,$88,$1b,$86,$21,$84,$21,$88,$1b,$86,$21,$21,$21,$88
	.byte $1b,$86,$21,$21,$84,$21,$88,$1b,$84,$21,$21,$86,$21,$21,$88,$1b
	.byte $86,$21,$84,$21,$88,$1b,$86,$21,$21,$21,$88,$1b,$86,$21,$21,$84
	.byte $21,$21,$21,$20,$81
	.byte $ff,$21
	.word @ref51
	.byte $ff,$21
	.word @ref51
@ref54:
	.byte $86,$21,$21,$88,$1b,$86,$21,$84,$21,$88,$1b,$86,$21,$21,$21,$88
	.byte $1b,$86,$21,$21,$84,$21,$88,$1b,$86,$21,$20,$20,$21,$21,$88,$1b
	.byte $86,$21,$84,$21,$88,$1b,$86,$21,$21,$21,$88,$1b,$86,$21,$21,$84
	.byte $21,$20,$88,$20,$86,$20,$88,$20,$20,$20
	.byte $ff,$24
	.word @ref54
@ref56:
	.byte $f9,$85
@ref57:
	.byte $d7,$1b,$1b,$84,$21,$21,$86,$21,$21,$84,$21,$21,$21,$20,$81
	.byte $ff,$21
	.word @ref51
	.byte $ff,$21
	.word @ref51
	.byte $ff,$21
	.word @ref51
	.byte $ff,$21
	.word @ref51
	.byte $ff,$21
	.word @ref51
	.byte $ff,$21
	.word @ref51
	.byte $fd
	.word @song0ch3loop

@song0ch4:
@ref64:
	.byte $f9,$85
@ref65:
	.byte $f9,$85
@song0ch4loop:
@ref66:
	.byte $f9,$85
@ref67:
	.byte $f9,$85
@ref68:
	.byte $f9,$85
@ref69:
	.byte $f9,$85
@ref70:
	.byte $f9,$85
@ref71:
	.byte $f9,$85
@ref72:
	.byte $f9,$85
@ref73:
	.byte $f9,$85
@ref74:
	.byte $f9,$85
@ref75:
	.byte $f9,$85
@ref76:
	.byte $f9,$85
@ref77:
	.byte $f9,$85
@ref78:
	.byte $f9,$85
@ref79:
	.byte $f9,$85
	.byte $fd
	.word @song0ch4loop


@song1ch0:
	.byte $fb,$07
@song1ch0loop:
@ref80:
	.byte $94,$32,$95,$33,$38,$89,$33,$38,$89,$3c,$85
@ref81:
	.byte $87,$2e,$95,$39,$33,$2f,$33,$39,$33,$39,$3c,$81
@ref82:
	.byte $32,$95,$33,$38,$89,$33,$38,$89,$3c,$85
	.byte $ff,$0c
	.word @ref81
@ref84:
	.byte $40,$95,$41,$42,$89,$40,$85,$3c,$85,$38,$85
@ref85:
	.byte $3c,$8d,$40,$85,$38,$8d,$32,$95
@ref86:
	.byte $32,$99,$32,$81
@ref87:
	.byte $39,$33,$33,$3c,$85,$3c,$40,$38,$85
@ref88:
	.byte $3c,$bd
@ref89:
	.byte $38,$9d,$3c,$9d
@ref90:
	.byte $3c,$9d,$3c,$85,$38,$85,$3c,$85,$40,$85
@ref91:
	.byte $46,$9d,$42,$8d,$46,$8d
@ref92:
	.byte $32,$bd
@ref93:
	.byte $2e,$bd
@ref94:
	.byte $38,$bd
@ref95:
	.byte $3c,$9d,$41,$41,$39,$39,$33,$33,$2f,$32,$81
@ref96:
	.byte $32,$bd
@ref97:
	.byte $2e,$bd
@ref98:
	.byte $38,$bd
	.byte $ff,$0b
	.word @ref95
@ref100:
	.byte $32,$bd
@ref101:
	.byte $2e,$bd
@ref102:
	.byte $2a,$bd
@ref103:
	.byte $2e,$a5,$00,$96,$1b,$21,$25,$29,$25,$20
@ref104:
	.byte $40,$95,$41,$42,$85,$40,$85,$3c,$85,$38,$85,$3c,$81
@ref105:
	.byte $83,$40,$85,$38,$a5,$39,$38,$85
@ref106:
	.byte $3c,$b1,$40,$85,$38,$81
@ref107:
	.byte $83,$33,$32,$85,$2f,$32,$89,$39,$32,$85,$33,$39,$3c,$89
@ref108:
	.byte $40,$95,$41,$42,$85,$40,$85,$46,$85,$40,$89
@ref109:
	.byte $3c,$9d,$41,$3c,$89,$41,$3c,$89
@ref110:
	.byte $3c,$95,$3d,$40,$85,$3c,$85,$38,$85,$3c,$89
@ref111:
	.byte $41,$41,$3d,$3d,$39,$39,$33,$33,$2f,$33,$39,$3d,$2e,$32,$38,$3c
	.byte $2e,$32,$38,$3c
	.byte $fd
	.word @song1ch0loop

@song1ch1:
@song1ch1loop:
@ref112:
	.byte $96,$28,$95,$25,$20,$89,$1a,$85,$21,$24,$89
@ref113:
	.byte $87,$16,$95,$1a,$85,$20,$85,$24,$85,$94,$21,$1a,$81
	.byte $ff,$0a
	.word @ref112
	.byte $ff,$0c
	.word @ref113
@ref116:
	.byte $96,$28,$95,$28,$85,$2a,$85,$28,$85,$24,$85,$20,$85
@ref117:
	.byte $24,$8d,$28,$85,$20,$8d,$1a,$95
@ref118:
	.byte $2f,$33,$33,$01,$2f,$33,$33,$38,$81
@ref119:
	.byte $83,$32,$85,$2e,$85,$32,$89
@ref120:
	.byte $24,$91,$39,$33,$38,$85,$32,$85,$33,$39,$3d,$41,$38,$81
@ref121:
	.byte $38,$9d,$3c,$85,$40,$85,$38,$85,$32,$85
	.byte $ff,$0e
	.word @ref120
@ref123:
	.byte $38,$9d,$39,$39,$3d,$3d,$41,$41,$43,$42,$81
@ref124:
	.byte $4b,$4b,$00,$85,$4b,$01,$4a,$85,$4a,$00,$83,$47,$4b,$51,$4b,$47
	.byte $4a,$81
@ref125:
	.byte $47,$47,$00,$85,$47,$01,$46,$85,$46,$00,$83,$47,$4b,$51,$4b,$47
	.byte $4a,$81
@ref126:
	.byte $38,$85,$32,$85,$2e,$85,$32,$85,$38,$85,$32,$85,$2e,$85,$32,$85
@ref127:
	.byte $3c,$9d,$29,$29,$21,$21,$1b,$1b,$17,$1a,$81
	.byte $ff,$12
	.word @ref124
	.byte $ff,$12
	.word @ref125
	.byte $ff,$10
	.word @ref126
	.byte $ff,$0b
	.word @ref127
@ref132:
	.byte $32,$95,$94,$33,$38,$89,$33,$38,$85,$3c,$89
@ref133:
	.byte $96,$2e,$95,$94,$33,$38,$89,$33,$38,$85,$3c,$89
@ref134:
	.byte $96,$2a,$95,$94,$33,$38,$89,$33,$38,$85,$3c,$89
@ref135:
	.byte $96,$2e,$95,$94,$33,$38,$89,$33,$39,$3d,$41,$3d,$38,$81
@ref136:
	.byte $32,$95,$33,$38,$89,$33,$38,$91
@ref137:
	.byte $2e,$95,$33,$38,$89,$33,$38,$85,$3c,$89
	.byte $ff,$06
	.word @ref106
@ref139:
	.byte $83,$32,$b9
@ref140:
	.byte $32,$85,$38,$8d,$33,$40,$85,$32,$85,$2e,$85,$40,$89
@ref141:
	.byte $38,$85,$3c,$8d,$33,$40,$85,$32,$85,$2e,$85,$40,$89
@ref142:
	.byte $2e,$b1,$3c,$89
@ref143:
	.byte $32,$9d,$2f,$33,$39,$3d,$2e,$32,$38,$3c,$2e,$32,$38,$3c
	.byte $fd
	.word @song1ch1loop

@song1ch2:
@song1ch2loop:
@ref144:
	.byte $92,$1a,$95,$17,$1b,$20,$95,$1b,$20,$81
@ref145:
	.byte $16,$9d,$21,$1b,$16,$85,$1b,$21,$1a,$85
@ref146:
	.byte $1a,$95,$17,$1b,$20,$95,$1b,$20,$81
	.byte $ff,$0a
	.word @ref145
@ref148:
	.byte $1b,$1b,$33,$1b,$1b,$1b,$33,$1b,$21,$21,$39,$21,$21,$21,$39,$20
	.byte $81
@ref149:
	.byte $17,$17,$2f,$17,$17,$17,$2f,$17,$21,$21,$39,$21,$21,$17,$21,$2e
	.byte $81
@ref150:
	.byte $2e,$99,$1a,$81
@ref151:
	.byte $21,$1a,$85,$24,$85,$24,$28,$20,$85
@ref152:
	.byte $1b,$1b,$1b,$00,$85,$1b,$1b,$17,$17,$1b,$1b,$1b,$21,$1b,$1b,$1a
	.byte $81
@ref153:
	.byte $17,$17,$2f,$17,$17,$2f,$17,$2f,$13,$13,$2b,$17,$17,$2f,$17,$20
	.byte $81
	.byte $ff,$11
	.word @ref152
	.byte $ff,$11
	.word @ref153
@ref156:
	.byte $1b,$1b,$33,$1b,$1b,$33,$1b,$33,$1b,$1b,$33,$1b,$1b,$33,$1b,$32
	.byte $81
@ref157:
	.byte $17,$17,$2f,$17,$17,$2f,$17,$2f,$17,$17,$2f,$17,$17,$2f,$17,$2e
	.byte $81
@ref158:
	.byte $21,$21,$39,$21,$21,$39,$21,$39,$21,$21,$39,$21,$21,$39,$21,$38
	.byte $81
@ref159:
	.byte $25,$25,$3d,$25,$25,$3d,$25,$3d,$25,$25,$3d,$25,$25,$3d,$25,$3c
	.byte $81
	.byte $ff,$11
	.word @ref156
	.byte $ff,$11
	.word @ref157
	.byte $ff,$11
	.word @ref158
	.byte $ff,$11
	.word @ref159
@ref164:
	.byte $1a,$bd
@ref165:
	.byte $16,$bd
@ref166:
	.byte $12,$bd
@ref167:
	.byte $16,$9d,$1b,$1b,$1b,$1b,$21,$21,$21,$20,$81
@ref168:
	.byte $1b,$1b,$1b,$33,$1b,$1b,$1b,$33,$1b,$1b,$1b,$33,$1b,$1b,$1b,$32
	.byte $81
@ref169:
	.byte $21,$21,$21,$39,$21,$21,$21,$39,$21,$21,$21,$39,$21,$21,$21,$38
	.byte $81
@ref170:
	.byte $17,$17,$17,$2f,$17,$17,$17,$2f,$17,$17,$17,$2f,$17,$17,$17,$2e
	.byte $81
@ref171:
	.byte $25,$25,$25,$3d,$25,$25,$25,$3d,$25,$25,$25,$3d,$25,$25,$25,$3c
	.byte $81
	.byte $ff,$11
	.word @ref168
	.byte $ff,$11
	.word @ref169
	.byte $ff,$11
	.word @ref170
	.byte $ff,$11
	.word @ref171
	.byte $fd
	.word @song1ch2loop

@song1ch3:
@song1ch3loop:
@ref176:
	.byte $9a,$21,$9c,$1b,$9a,$21,$9c,$1b,$98,$21,$9a,$21,$21,$9c,$1a,$1a
	.byte $1b,$9a,$21,$21,$9c,$1b,$98,$21,$9c,$1b,$9a,$21,$20,$81
@ref177:
	.byte $21,$9c,$1b,$9a,$21,$9c,$1b,$98,$21,$9a,$21,$21,$9c,$1a,$1a,$1b
	.byte $9a,$21,$21,$9c,$1b,$98,$21,$9c,$1b,$9a,$21,$98,$20,$81
	.byte $ff,$12
	.word @ref176
	.byte $ff,$12
	.word @ref177
	.byte $ff,$12
	.word @ref176
	.byte $ff,$12
	.word @ref177
@ref182:
	.byte $9f
@ref183:
	.byte $9f
@ref184:
	.byte $9a,$21,$21,$98,$21,$9c,$1a,$1a,$1b,$9a,$21,$98,$21,$9a,$21,$9c
	.byte $1b,$9a,$20,$20,$98,$21,$9c,$1b,$1b,$98,$21,$21,$20,$20
@ref185:
	.byte $9a,$21,$21,$98,$21,$9c,$1a,$1a,$1b,$9a,$21,$98,$21,$9a,$21,$9c
	.byte $1b,$9a,$20,$20,$98,$21,$9a,$20,$20,$98,$21,$20,$20,$20,$20,$9a
	.byte $20,$20
@ref186:
	.byte $21,$21,$98,$21,$9c,$1a,$1a,$1b,$9a,$21,$98,$21,$9a,$21,$9c,$1b
	.byte $9a,$20,$20,$98,$21,$9c,$1b,$1b,$98,$21,$21,$20,$20
	.byte $ff,$16
	.word @ref185
@ref188:
	.byte $21,$9c,$1b,$1b,$1b,$98,$21,$9a,$21,$21,$9c,$1a,$1a,$1b,$9a,$21
	.byte $98,$21,$9c,$1b,$1b,$98,$21,$21,$9a,$20,$20
@ref189:
	.byte $21,$9c,$1b,$1b,$1b,$98,$21,$9a,$21,$21,$9c,$1a,$1a,$1b,$9a,$21
	.byte $98,$21,$9c,$1b,$1b,$9a,$21,$21,$98,$20,$20
@ref190:
	.byte $9a,$21,$9c,$1b,$1b,$1b,$98,$21,$9a,$21,$21,$9c,$1a,$1a,$1b,$9a
	.byte $21,$98,$21,$9c,$1b,$1b,$98,$21,$21,$9a,$20,$20
	.byte $ff,$12
	.word @ref189
	.byte $ff,$12
	.word @ref190
	.byte $ff,$12
	.word @ref189
	.byte $ff,$13
	.word @ref184
	.byte $ff,$16
	.word @ref185
@ref196:
	.byte $bf
@ref197:
	.byte $bf
@ref198:
	.byte $9c,$1a,$85,$1a,$85,$1a,$85,$1a,$85,$1a,$85,$1a,$85,$1a,$85,$1b
	.byte $1a,$1a
@ref199:
	.byte $1a,$85,$1a,$85,$1a,$85,$1b,$1a,$1a,$98,$20,$20,$9a,$20,$20,$98
	.byte $20,$20,$20,$20,$9a,$20,$20,$98,$20,$20,$9a,$20,$20,$98,$20,$20
	.byte $ff,$13
	.word @ref184
	.byte $ff,$16
	.word @ref185
	.byte $ff,$13
	.word @ref186
	.byte $ff,$16
	.word @ref185
	.byte $ff,$13
	.word @ref186
	.byte $ff,$16
	.word @ref185
	.byte $ff,$13
	.word @ref186
@ref207:
	.byte $9a,$21,$21,$98,$21,$9c,$1a,$1a,$1b,$9a,$21,$98,$21,$9a,$21,$98
	.byte $20,$20,$9a,$20,$20,$98,$20,$20,$20,$20,$9a,$20,$20,$98,$20,$20
	.byte $9a,$20,$20,$98,$20,$20
	.byte $fd
	.word @song1ch3loop

@song1ch4:
@song1ch4loop:
@ref208:
	.byte $bf
@ref209:
	.byte $bf
@ref210:
	.byte $bf
@ref211:
	.byte $bf
@ref212:
	.byte $bf
@ref213:
	.byte $bf
@ref214:
	.byte $9f
@ref215:
	.byte $9f
@ref216:
	.byte $bf
@ref217:
	.byte $bf
@ref218:
	.byte $bf
@ref219:
	.byte $bf
@ref220:
	.byte $bf
@ref221:
	.byte $bf
@ref222:
	.byte $bf
@ref223:
	.byte $bf
@ref224:
	.byte $bf
@ref225:
	.byte $bf
@ref226:
	.byte $bf
@ref227:
	.byte $bf
@ref228:
	.byte $bf
@ref229:
	.byte $bf
@ref230:
	.byte $bf
@ref231:
	.byte $bf
@ref232:
	.byte $bf
@ref233:
	.byte $bf
@ref234:
	.byte $bf
@ref235:
	.byte $bf
@ref236:
	.byte $bf
@ref237:
	.byte $bf
@ref238:
	.byte $bf
@ref239:
	.byte $bf
	.byte $fd
	.word @song1ch4loop
