;this file for FamiTone2 library generated by text2data tool

music_music_data:
	.byte 2
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256
	.word @song1ch0,@song1ch1,@song1ch2,@song1ch3,@song1ch4,307,256

@instruments:
	.byte $30 ;instrument $00
	.word @env2,@env0,@env0
	.byte $00
	.byte $30 ;instrument $01
	.word @env1,@env0,@env14
	.byte $00
	.byte $70 ;instrument $02
	.word @env5,@env0,@env0
	.byte $00
	.byte $30 ;instrument $04
	.word @env6,@env12,@env0
	.byte $00
	.byte $30 ;instrument $05
	.word @env10,@env0,@env0
	.byte $00
	.byte $30 ;instrument $06
	.word @env7,@env0,@env0
	.byte $00
	.byte $30 ;instrument $07
	.word @env1,@env11,@env0
	.byte $00
	.byte $70 ;instrument $08
	.word @env3,@env0,@env15
	.byte $00
	.byte $70 ;instrument $09
	.word @env4,@env0,@env15
	.byte $00
	.byte $30 ;instrument $0a
	.word @env3,@env0,@env15
	.byte $00
	.byte $70 ;instrument $0c
	.word @env8,@env13,@env0
	.byte $00
	.byte $70 ;instrument $0d
	.word @env9,@env13,@env0
	.byte $00

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $ca,$00,$00
@env2:
	.byte $cf,$00,$00
@env3:
	.byte $cc,$cb,$ca,$ca,$c9,$03,$c8,$03,$c7,$07,$c6,$08,$c5,$0a,$c4,$0c
	.byte $c3,$0c,$c2,$12,$c1,$19,$c0,$00,$16
@env4:
	.byte $c4,$02,$c3,$0c,$c2,$0b,$c1,$12,$c0,$00,$08
@env5:
	.byte $c7,$07,$c4,$05,$c7,$07,$c7,$00,$06
@env6:
	.byte $ca,$c8,$c6,$c4,$c3,$c2,$c0,$00,$06
@env7:
	.byte $c7,$c2,$c0,$00,$02
@env8:
	.byte $c8,$c8,$c7,$c7,$c6,$c6,$c5,$c5,$c4,$c4,$c3,$c2,$c1,$00,$0c
@env9:
	.byte $c7,$02,$c6,$02,$c5,$02,$c4,$c4,$c2,$00,$08
@env10:
	.byte $cd,$cb,$c9,$c7,$c5,$c4,$c3,$c2,$c0,$00,$08
@env11:
	.byte $c0,$05,$bf,$be,$bd,$bc,$bb,$ba,$b9,$b8,$b7,$b6,$b5,$b4,$b3,$b2
	.byte $b1,$b0,$af,$ae,$ad,$ac,$ab,$aa,$a9,$a8,$a8,$a7,$a7,$a6,$a6,$a5
	.byte $a5,$a4,$a4,$a3,$a3,$a2,$a2,$a1,$a1,$00,$28
@env12:
	.byte $c7,$c3,$c0,$bd,$00,$02
@env13:
	.byte $c0,$c0,$c4,$c4,$c7,$c7,$00,$00
@env14:
	.byte $c0,$0e,$bf,$be,$bd,$bc,$bd,$be,$bf,$c0,$00,$02
@env15:
	.byte $c0,$0f,$c1,$02,$c2,$02,$c1,$02,$c0,$c0,$c0,$00,$02


@song0ch0:
	.byte $fb,$04
@ref0:
	.byte $94,$33,$33,$96,$32,$85,$90,$32,$85,$38,$85,$94,$35,$35,$96,$34
	.byte $85,$90,$40,$85,$40,$85
@ref1:
	.byte $94,$39,$39,$96,$32,$85,$90,$32,$85,$38,$85,$94,$3d,$3d,$96,$3c
	.byte $89,$90,$42,$85,$42,$81
@ref2:
	.byte $94,$33,$33,$96,$32,$85,$90,$32,$8d,$94,$2f,$2f,$96,$2e,$85,$90
	.byte $38,$8d
@ref3:
	.byte $94,$39,$39,$96,$32,$85,$90,$38,$8d,$8e,$50,$4e,$4c,$4a,$48,$46
	.byte $44,$42,$40,$3e,$3c,$3a,$38,$36,$34,$32
@song0ch0loop:
	.byte $ff,$10
	.word @ref0
	.byte $ff,$10
	.word @ref1
	.byte $ff,$0c
	.word @ref2
@ref7:
	.byte $94,$39,$39,$96,$32,$85,$90,$38,$8d,$94,$3d,$3d,$96,$3c,$85,$94
	.byte $41,$41,$96,$40,$85
@ref8:
	.byte $82,$38,$95,$32,$9d,$32,$85
@ref9:
	.byte $3c,$85,$40,$8d,$38,$8d,$32,$85,$2e,$85,$32,$85
@ref10:
	.byte $38,$95,$32,$9d,$32,$85
@ref11:
	.byte $3c,$85,$40,$8d,$42,$8d,$40,$95
@ref12:
	.byte $84,$59,$55,$51,$4b,$59,$55,$51,$4b,$5b,$59,$55,$51,$5b,$59,$55
	.byte $50,$81
@ref13:
	.byte $5f,$5b,$59,$55,$5f,$5b,$59,$55,$63,$5f,$5b,$59,$63,$5f,$5b,$58
	.byte $81
@ref14:
	.byte $41,$3d,$39,$33,$41,$3d,$39,$33,$43,$41,$3d,$39,$43,$41,$3d,$38
	.byte $81
@ref15:
	.byte $47,$43,$41,$3d,$47,$43,$41,$3d,$82,$42,$89,$46,$89,$46,$85
@ref16:
	.byte $46,$95,$42,$9d,$40,$85
@ref17:
	.byte $42,$95,$40,$8d,$3c,$85,$38,$85,$3c,$85
@ref18:
	.byte $38,$b5,$36,$85
@ref19:
	.byte $38,$85,$3c,$8d,$38,$8d,$32,$95
@ref20:
	.byte $32,$b5,$36,$85
@ref21:
	.byte $38,$85,$3c,$8d,$42,$8d,$40,$95
	.byte $ff,$10
	.word @ref0
	.byte $ff,$10
	.word @ref1
	.byte $ff,$0c
	.word @ref2
	.byte $ff,$16
	.word @ref3
	.byte $fd
	.word @song0ch0loop

@song0ch1:
@ref26:
	.byte $8e,$38,$85,$32,$85,$38,$85,$3d,$40,$85,$41,$40,$85,$40,$8d
@ref27:
	.byte $87,$32,$85,$38,$85,$3c,$85,$40,$89,$42,$89,$43,$40,$81
@ref28:
	.byte $40,$85,$32,$8d,$2e,$85,$32,$85,$38,$8d,$3c,$85
@ref29:
	.byte $87,$38,$8d,$36,$8d,$33,$37,$32,$8d
@song0ch1loop:
	.byte $ff,$0e
	.word @ref26
	.byte $ff,$0e
	.word @ref27
	.byte $ff,$0c
	.word @ref28
	.byte $ff,$09
	.word @ref29
@ref34:
	.byte $50,$95,$4a,$9d,$4a,$85
@ref35:
	.byte $54,$85,$58,$8d,$50,$8d,$4a,$85,$46,$85,$4a,$85
	.byte $ff,$06
	.word @ref34
@ref37:
	.byte $54,$85,$58,$8d,$5a,$8d,$58,$95
@ref38:
	.byte $4a,$95,$46,$9d,$46,$85
@ref39:
	.byte $50,$95,$4a,$8d,$46,$85,$4a,$85,$46,$85
	.byte $ff,$06
	.word @ref38
@ref41:
	.byte $50,$85,$4e,$95,$42,$89,$46,$89,$46,$85
	.byte $ff,$06
	.word @ref16
	.byte $ff,$0a
	.word @ref17
@ref44:
	.byte $38,$b5,$36,$85
	.byte $ff,$08
	.word @ref19
@ref46:
	.byte $32,$b5,$36,$85
	.byte $ff,$08
	.word @ref21
@ref48:
	.byte $38,$85,$32,$85,$38,$85,$3d,$40,$85,$41,$40,$85,$40,$8d
	.byte $ff,$0e
	.word @ref27
	.byte $ff,$0c
	.word @ref28
	.byte $ff,$09
	.word @ref29
	.byte $fd
	.word @song0ch1loop

@song0ch2:
@ref52:
	.byte $00,$bd
@ref53:
	.byte $bf
@ref54:
	.byte $80,$1a,$9d,$16,$9d
@ref55:
	.byte $20,$9d,$8c,$39,$39,$51,$39,$39,$51,$3d,$54,$81
@song0ch2loop:
@ref56:
	.byte $8c,$33,$01,$4b,$01,$33,$33,$4b,$33,$01,$33,$01,$33,$2f,$2f,$47
	.byte $42,$81
@ref57:
	.byte $39,$01,$51,$01,$39,$39,$51,$3d,$01,$3d,$01,$3d,$39,$39,$51,$34
	.byte $81
@ref58:
	.byte $33,$01,$4b,$01,$33,$33,$4b,$33,$01,$33,$01,$33,$2f,$2f,$47,$42
	.byte $81
@ref59:
	.byte $39,$01,$51,$01,$39,$39,$51,$3d,$39,$39,$51,$39,$39,$51,$3d,$54
	.byte $81
@ref60:
	.byte $80,$33,$33,$33,$33,$33,$33,$33,$33,$39,$39,$39,$39,$39,$39,$39
	.byte $38,$81
@ref61:
	.byte $3d,$3d,$3d,$3d,$3d,$3d,$3d,$3d,$39,$39,$39,$39,$39,$39,$35,$34
	.byte $81
@ref62:
	.byte $33,$33,$4b,$33,$33,$4b,$33,$4b,$39,$39,$51,$39,$39,$51,$39,$50
	.byte $81
@ref63:
	.byte $3d,$3d,$55,$3d,$3d,$55,$3d,$55,$39,$39,$51,$39,$39,$51,$35,$4c
	.byte $81
@ref64:
	.byte $33,$33,$33,$33,$33,$33,$33,$33,$39,$39,$39,$39,$39,$39,$39,$38
	.byte $81
	.byte $ff,$11
	.word @ref61
	.byte $ff,$11
	.word @ref64
	.byte $ff,$11
	.word @ref61
@ref68:
	.byte $32,$8d,$01,$4b,$33,$4b,$39,$01,$51,$39,$39,$51,$39,$50,$81
@ref69:
	.byte $3c,$8d,$01,$55,$3d,$55,$39,$01,$51,$39,$39,$51,$35,$4c,$81
	.byte $ff,$0f
	.word @ref68
	.byte $ff,$0f
	.word @ref69
	.byte $ff,$11
	.word @ref64
	.byte $ff,$11
	.word @ref61
@ref74:
	.byte $00,$bd
@ref75:
	.byte $bf
@ref76:
	.byte $1a,$9d,$16,$9d
	.byte $ff,$0b
	.word @ref55
	.byte $fd
	.word @song0ch2loop

@song0ch3:
@ref78:
	.byte $00,$bd
@ref79:
	.byte $bf
@ref80:
	.byte $bf
@ref81:
	.byte $9f,$86,$21,$21,$88,$21,$21,$86,$21,$21,$21,$20,$81
@song0ch3loop:
@ref82:
	.byte $88,$21,$8a,$1b,$86,$21,$8a,$1b,$88,$21,$21,$86,$21,$8a,$1b,$88
	.byte $21,$21,$86,$21,$88,$21,$8a,$1b,$88,$21,$86,$21,$20,$81
@ref83:
	.byte $88,$21,$8a,$1b,$86,$21,$8a,$1b,$88,$21,$21,$86,$21,$88,$21,$86
	.byte $21,$21,$88,$21,$21,$86,$21,$21,$21,$20,$81
	.byte $ff,$11
	.word @ref82
	.byte $ff,$11
	.word @ref83
	.byte $ff,$11
	.word @ref82
	.byte $ff,$11
	.word @ref82
	.byte $ff,$11
	.word @ref82
	.byte $ff,$11
	.word @ref82
	.byte $ff,$11
	.word @ref82
	.byte $ff,$11
	.word @ref83
	.byte $ff,$11
	.word @ref82
	.byte $ff,$11
	.word @ref83
@ref94:
	.byte $21,$21,$21,$20,$85,$21,$21,$21,$20,$85,$20,$85,$21,$20,$89
@ref95:
	.byte $21,$21,$21,$20,$85,$21,$21,$21,$20,$85,$20,$85,$21,$21,$21,$20
	.byte $81
	.byte $ff,$11
	.word @ref82
	.byte $ff,$11
	.word @ref82
@ref98:
	.byte $88,$21,$8a,$1b,$1b,$1b,$1b,$1b,$88,$21,$8a,$1b,$86,$21,$8a,$1b
	.byte $88,$21,$8a,$1b,$1b,$1b,$1b,$1a,$81
@ref99:
	.byte $88,$21,$8a,$1b,$1b,$88,$21,$86,$21,$21,$88,$21,$8a,$1b,$86,$21
	.byte $8a,$1b,$88,$21,$21,$86,$21,$88,$21,$86,$21,$20,$81
@ref100:
	.byte $00,$bd
@ref101:
	.byte $bf
@ref102:
	.byte $bf
@ref103:
	.byte $9f,$21,$21,$88,$21,$21,$86,$21,$21,$21,$20,$81
	.byte $fd
	.word @song0ch3loop

@song0ch4:
@ref104:
	.byte $bf
@ref105:
	.byte $bf
@ref106:
	.byte $bf
@ref107:
	.byte $bf
@song0ch4loop:
@ref108:
	.byte $bf
@ref109:
	.byte $bf
@ref110:
	.byte $bf
@ref111:
	.byte $bf
@ref112:
	.byte $bf
@ref113:
	.byte $bf
@ref114:
	.byte $bf
@ref115:
	.byte $bf
@ref116:
	.byte $bf
@ref117:
	.byte $bf
@ref118:
	.byte $bf
@ref119:
	.byte $bf
@ref120:
	.byte $bf
@ref121:
	.byte $bf
@ref122:
	.byte $bf
@ref123:
	.byte $bf
@ref124:
	.byte $bf
@ref125:
	.byte $bf
@ref126:
	.byte $bf
@ref127:
	.byte $bf
@ref128:
	.byte $bf
@ref129:
	.byte $bf
	.byte $fd
	.word @song0ch4loop


@song1ch0:
	.byte $fb,$06
@song1ch0loop:
@ref130:
	.byte $f9,$85
	.byte $fd
	.word @song1ch0loop

@song1ch1:
@song1ch1loop:
@ref131:
	.byte $f9,$85
	.byte $fd
	.word @song1ch1loop

@song1ch2:
@song1ch2loop:
@ref132:
	.byte $f9,$85
	.byte $fd
	.word @song1ch2loop

@song1ch3:
@song1ch3loop:
@ref133:
	.byte $86,$0f,$0e,$0e,$0f,$0f,$0e,$0e,$0e,$0e,$0e,$0e,$0e,$0e,$0f,$0e
	.byte $0e,$0f,$0f,$0f,$0f,$0e,$0e,$0e,$0e,$0f,$0e,$0e,$0f,$0f,$0f,$0f
	.byte $0e,$0e,$0e,$0e,$0f,$0f,$0e,$0e,$0f,$0f,$0e,$0e,$0f,$0e,$81
	.byte $fd
	.word @song1ch3loop

@song1ch4:
@song1ch4loop:
@ref134:
	.byte $f9,$85
	.byte $fd
	.word @song1ch4loop
